// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM
// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM
// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY
// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS
// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS
module TrapHandleModule(
  input         io_in_trapInfo_valid,
  input  [63:0] io_in_trapInfo_bits_trapVec,
  input  [63:0] io_in_trapInfo_bits_intrVec,
  input         io_in_trapInfo_bits_isInterrupt,
  input         io_in_trapInfo_bits_singleStep,
  input         io_in_trapInfo_bits_triggerFire,
  input  [1:0]  io_in_privState_PRVM,
  input         io_in_privState_V,
  input         io_in_mideleg_SSI,
  input         io_in_mideleg_STI,
  input         io_in_mideleg_SEI,
  input         io_in_mideleg_LCOFI,
  input         io_in_medeleg_EX_IAM,
  input         io_in_medeleg_EX_IAF,
  input         io_in_medeleg_EX_II,
  input         io_in_medeleg_EX_LAM,
  input         io_in_medeleg_EX_LAF,
  input         io_in_medeleg_EX_SAM,
  input         io_in_medeleg_EX_SAF,
  input         io_in_medeleg_EX_UCALL,
  input         io_in_medeleg_EX_HSCALL,
  input         io_in_medeleg_EX_VSCALL,
  input         io_in_medeleg_EX_IPF,
  input         io_in_medeleg_EX_LPF,
  input         io_in_medeleg_EX_SPF,
  input         io_in_medeleg_EX_IGPF,
  input         io_in_medeleg_EX_LGPF,
  input         io_in_medeleg_EX_VI,
  input         io_in_medeleg_EX_SGPF,
  input         io_in_hideleg_VSSI,
  input         io_in_hideleg_VSTI,
  input         io_in_hideleg_VSEI,
  input         io_in_hideleg_LCOFI,
  input         io_in_hedeleg_EX_IAM,
  input         io_in_hedeleg_EX_IAF,
  input         io_in_hedeleg_EX_II,
  input         io_in_hedeleg_EX_BP,
  input         io_in_hedeleg_EX_LAM,
  input         io_in_hedeleg_EX_LAF,
  input         io_in_hedeleg_EX_SAM,
  input         io_in_hedeleg_EX_SAF,
  input         io_in_hedeleg_EX_UCALL,
  input         io_in_hedeleg_EX_IPF,
  input         io_in_hedeleg_EX_LPF,
  input         io_in_hedeleg_EX_SPF,
  input  [1:0]  io_in_mtvec_mode,
  input  [61:0] io_in_mtvec_addr,
  input  [1:0]  io_in_stvec_mode,
  input  [61:0] io_in_stvec_addr,
  input  [1:0]  io_in_vstvec_mode,
  input  [61:0] io_in_vstvec_addr,
  output [1:0]  io_out_entryPrivState_PRVM,
  output        io_out_entryPrivState_V,
  output        io_out_causeNO_Interrupt,
  output [62:0] io_out_causeNO_ExceptionCode,
  output [63:0] io_out_pcFromXtvec
);

  wire        hasIR = io_in_trapInfo_valid & io_in_trapInfo_bits_isInterrupt;
  wire [23:0] hasEXVec =
    io_in_trapInfo_valid & ~io_in_trapInfo_bits_isInterrupt
      ? io_in_trapInfo_bits_trapVec[23:0]
      : 24'h0;
  wire [42:0] hasIRVec = hasIR ? io_in_trapInfo_bits_intrVec[43:1] : 43'h0;
  wire        highestPrioIRVec_43 = hasIRVec[42];
  wire        highestPrioIRVec_1 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8])}) & hasIRVec[0];
  wire        highestPrioIRVec_2 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8]),
       ~(hasIRVec[0]),
       ~(hasIRVec[4]),
       ~(hasIRVec[11]),
       ~(hasIRVec[9])}) & hasIRVec[1];
  wire        highestPrioIRVec_3 =
    (&{~highestPrioIRVec_43, ~(hasIRVec[10])}) & hasIRVec[2];
  wire        highestPrioIRVec_5 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8]),
       ~(hasIRVec[0])}) & hasIRVec[4];
  wire        highestPrioIRVec_6 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8]),
       ~(hasIRVec[0]),
       ~(hasIRVec[4]),
       ~(hasIRVec[11]),
       ~(hasIRVec[9]),
       ~(hasIRVec[1])}) & hasIRVec[5];
  wire        highestPrioIRVec_7 =
    (&{~highestPrioIRVec_43, ~(hasIRVec[10]), ~(hasIRVec[2])}) & hasIRVec[6];
  wire        highestPrioIRVec_9 =
    (&{~highestPrioIRVec_43, ~(hasIRVec[10]), ~(hasIRVec[2]), ~(hasIRVec[6])})
    & hasIRVec[8];
  wire        highestPrioIRVec_10 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8]),
       ~(hasIRVec[0]),
       ~(hasIRVec[4]),
       ~(hasIRVec[11])}) & hasIRVec[9];
  wire        highestPrioIRVec_11 = ~highestPrioIRVec_43 & hasIRVec[10];
  wire        highestPrioIRVec_12 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8]),
       ~(hasIRVec[0]),
       ~(hasIRVec[4])}) & hasIRVec[11];
  wire        highestPrioIRVec_13 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8]),
       ~(hasIRVec[0]),
       ~(hasIRVec[4]),
       ~(hasIRVec[11]),
       ~(hasIRVec[9]),
       ~(hasIRVec[1]),
       ~(hasIRVec[5])}) & hasIRVec[12];
  wire        highestPrioIRVec_35 =
    (&{~highestPrioIRVec_43,
       ~(hasIRVec[10]),
       ~(hasIRVec[2]),
       ~(hasIRVec[6]),
       ~(hasIRVec[8]),
       ~(hasIRVec[0]),
       ~(hasIRVec[4]),
       ~(hasIRVec[11]),
       ~(hasIRVec[9]),
       ~(hasIRVec[1]),
       ~(hasIRVec[5]),
       ~(hasIRVec[12])}) & hasIRVec[34];
  wire        highestPrioEXVec_1 =
    (&{~(hasEXVec[3]), ~(hasEXVec[12]), ~(hasEXVec[20])}) & hasEXVec[1];
  wire        highestPrioEXVec_2 =
    (&{~(hasEXVec[3]), ~(hasEXVec[12]), ~(hasEXVec[20]), ~(hasEXVec[1])}) & hasEXVec[2];
  wire        highestPrioEXVec_4 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6])}) & hasEXVec[4];
  wire        highestPrioEXVec_5 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13]),
       ~(hasEXVec[23]),
       ~(hasEXVec[21]),
       ~(hasEXVec[7])}) & hasEXVec[5];
  wire        highestPrioEXVec_6 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8])}) & hasEXVec[6];
  wire        highestPrioEXVec_7 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13]),
       ~(hasEXVec[23]),
       ~(hasEXVec[21])}) & hasEXVec[7];
  wire        highestPrioEXVec_8 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10])}) & hasEXVec[8];
  wire        highestPrioEXVec_9 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11])}) & hasEXVec[9];
  wire        highestPrioEXVec_10 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9])}) & hasEXVec[10];
  wire        highestPrioEXVec_11 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0])}) & hasEXVec[11];
  wire        highestPrioEXVec_12 = ~(hasEXVec[3]) & hasEXVec[12];
  wire        highestPrioEXVec_13 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15])}) & hasEXVec[13];
  wire        highestPrioEXVec_15 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4])}) & hasEXVec[15];
  wire        highestPrioEXVec_20 = (&{~(hasEXVec[3]), ~(hasEXVec[12])}) & hasEXVec[20];
  wire        highestPrioEXVec_21 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13]),
       ~(hasEXVec[23])}) & hasEXVec[21];
  wire        highestPrioEXVec_22 =
    (&{~(hasEXVec[3]), ~(hasEXVec[12]), ~(hasEXVec[20]), ~(hasEXVec[1]), ~(hasEXVec[2])})
    & hasEXVec[22];
  wire        highestPrioEXVec_23 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13])}) & hasEXVec[23];
  wire [12:0] hsIRVec =
    {highestPrioIRVec_13,
     highestPrioIRVec_12,
     highestPrioIRVec_11,
     highestPrioIRVec_10,
     highestPrioIRVec_9,
     1'h0,
     highestPrioIRVec_7,
     highestPrioIRVec_6,
     highestPrioIRVec_5,
     1'h0,
     highestPrioIRVec_3,
     highestPrioIRVec_2,
     highestPrioIRVec_1}
    & {io_in_mideleg_LCOFI,
       3'h5,
       io_in_mideleg_SEI,
       3'h1,
       io_in_mideleg_STI,
       3'h1,
       io_in_mideleg_SSI};
  wire [11:0] vsIRVec =
    hsIRVec[12:1]
    & {io_in_hideleg_LCOFI,
       2'h0,
       io_in_hideleg_VSEI,
       3'h0,
       io_in_hideleg_VSTI,
       3'h0,
       io_in_hideleg_VSSI};
  wire [23:0] hsEXVec =
    {highestPrioEXVec_23,
     highestPrioEXVec_22,
     highestPrioEXVec_21,
     highestPrioEXVec_20,
     4'h0,
     highestPrioEXVec_15,
     1'h0,
     highestPrioEXVec_13,
     highestPrioEXVec_12,
     highestPrioEXVec_11,
     highestPrioEXVec_10,
     highestPrioEXVec_9,
     highestPrioEXVec_8,
     highestPrioEXVec_7,
     highestPrioEXVec_6,
     highestPrioEXVec_5,
     highestPrioEXVec_4,
     hasEXVec[3],
     highestPrioEXVec_2,
     highestPrioEXVec_1,
     (&{~(hasEXVec[3]),
        ~(hasEXVec[12]),
        ~(hasEXVec[20]),
        ~(hasEXVec[1]),
        ~(hasEXVec[2]),
        ~(hasEXVec[22])}) & hasEXVec[0]}
    & {io_in_medeleg_EX_SGPF,
       io_in_medeleg_EX_VI,
       io_in_medeleg_EX_LGPF,
       io_in_medeleg_EX_IGPF,
       4'h0,
       io_in_medeleg_EX_SPF,
       1'h0,
       io_in_medeleg_EX_LPF,
       io_in_medeleg_EX_IPF,
       1'h0,
       io_in_medeleg_EX_VSCALL,
       io_in_medeleg_EX_HSCALL,
       io_in_medeleg_EX_UCALL,
       io_in_medeleg_EX_SAF,
       io_in_medeleg_EX_SAM,
       io_in_medeleg_EX_LAF,
       io_in_medeleg_EX_LAM,
       1'h0,
       io_in_medeleg_EX_II,
       io_in_medeleg_EX_IAF,
       io_in_medeleg_EX_IAM};
  wire [15:0] vsEXVec =
    hsEXVec[15:0]
    & {io_in_hedeleg_EX_SPF,
       1'h0,
       io_in_hedeleg_EX_LPF,
       io_in_hedeleg_EX_IPF,
       3'h0,
       io_in_hedeleg_EX_UCALL,
       io_in_hedeleg_EX_SAF,
       io_in_hedeleg_EX_SAM,
       io_in_hedeleg_EX_LAF,
       io_in_hedeleg_EX_LAM,
       io_in_hedeleg_EX_BP,
       io_in_hedeleg_EX_II,
       io_in_hedeleg_EX_IAF,
       io_in_hedeleg_EX_IAM};
  wire        handleTrapUnderHS_v_PrvmIsM = &io_in_privState_PRVM;
  wire        handleTrapUnderHS_isModeM = handleTrapUnderHS_v_PrvmIsM;
  wire        handleTrapUnderHS =
    ~handleTrapUnderHS_isModeM
    & ((|{hsEXVec[23:20], hsEXVec[15], hsEXVec[13:12], hsEXVec[10:4], hsEXVec[2:0]})
       | (|{hsIRVec[12:11], hsIRVec[9:8], hsIRVec[5:4], hsIRVec[1:0]}));
  wire        handleTrapUnderVS =
    io_in_privState_V
    & ((|{vsEXVec[15], vsEXVec[13:12], vsEXVec[8:4], vsEXVec[2:0]})
       | (|{vsIRVec[11], vsIRVec[8], vsIRVec[4], vsIRVec[0]}));
  wire        _GEN = highestPrioEXVec_22 | highestPrioEXVec_6;
  wire        _GEN_0 = highestPrioEXVec_15 | highestPrioEXVec_23 | highestPrioEXVec_7;
  wire        _GEN_1 = highestPrioEXVec_13 | highestPrioEXVec_21 | highestPrioEXVec_5;
  wire [2:0]  _exceptionRegular_T_7 =
    {_GEN_0, _GEN, _GEN_1}
    | {highestPrioEXVec_11 | hasEXVec[3],
       highestPrioEXVec_10 | highestPrioEXVec_2,
       highestPrioEXVec_9 | highestPrioEXVec_1};
  wire        _GEN_2 = highestPrioIRVec_43 | highestPrioIRVec_11;
  wire        _GEN_3 = highestPrioIRVec_13 | highestPrioIRVec_5;
  wire        _GEN_4 =
    highestPrioIRVec_7 | _GEN_2 | highestPrioIRVec_35 | highestPrioIRVec_3;
  wire [5:0]  interruptNO =
    {|{highestPrioIRVec_43, highestPrioIRVec_35},
     1'h0,
     |{highestPrioIRVec_13,
       highestPrioIRVec_12,
       _GEN_2,
       highestPrioIRVec_10,
       highestPrioIRVec_9},
     |{highestPrioIRVec_7, highestPrioIRVec_6, _GEN_3, highestPrioIRVec_12},
     |{_GEN_4, highestPrioIRVec_6 | highestPrioIRVec_10 | highestPrioIRVec_2},
     _GEN_4 | _GEN_3 | highestPrioIRVec_9 | highestPrioIRVec_1};
  assign io_out_entryPrivState_PRVM = {~(handleTrapUnderVS | handleTrapUnderHS), 1'h1};
  assign io_out_entryPrivState_V = handleTrapUnderVS;
  assign io_out_causeNO_Interrupt = hasIR;
  assign io_out_causeNO_ExceptionCode =
    {57'h0,
     hasIR
       ? interruptNO
       : io_in_trapInfo_bits_singleStep | io_in_trapInfo_bits_triggerFire
           ? 6'h3
           : {1'h0,
              |{highestPrioEXVec_23,
                highestPrioEXVec_22,
                highestPrioEXVec_21,
                highestPrioEXVec_20},
              |{highestPrioEXVec_15,
                highestPrioEXVec_13,
                highestPrioEXVec_12,
                highestPrioEXVec_11,
                highestPrioEXVec_10,
                highestPrioEXVec_9,
                highestPrioEXVec_8},
              |{_GEN_0,
                _GEN,
                _GEN_1,
                highestPrioEXVec_12 | highestPrioEXVec_20 | highestPrioEXVec_4},
              |(_exceptionRegular_T_7[2:1]),
              _exceptionRegular_T_7[2] | _exceptionRegular_T_7[0]}};
  assign io_out_pcFromXtvec =
    {62'((handleTrapUnderVS
            ? io_in_vstvec_addr
            : handleTrapUnderHS ? io_in_stvec_addr : io_in_mtvec_addr)
         + {56'h0,
            (handleTrapUnderVS
               ? io_in_vstvec_mode
               : handleTrapUnderHS ? io_in_stvec_mode : io_in_mtvec_mode) == 2'h1 & hasIR
              ? interruptNO
              : 6'h0}),
     2'h0};
endmodule

