// Generated by CIRCT firtool-1.74.0
module array_4(
  input  [8:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [15:0] R0_data,
  input  [8:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [15:0] W0_data,
  input  [7:0]  W0_mask
);

  array_4_ext array_4_ext (
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (W0_en),
    .W0_clk  (W0_clk),
    .W0_data (W0_data),
    .W0_mask (W0_mask)
  );
endmodule

