// Generated by CIRCT firtool-1.74.0
module array_mcp2_0(
  input  [11:0]  RW0_addr,
  input          RW0_en,
  input          RW0_clk,
  input          RW0_wmode,
  input  [511:0] RW0_wdata,
  output [511:0] RW0_rdata
);

  array_mcp2_0_ext array_mcp2_0_ext (
    .RW0_addr  (RW0_addr),
    .RW0_en    (RW0_en),
    .RW0_clk   (RW0_clk),
    .RW0_wmode (RW0_wmode),
    .RW0_wdata (RW0_wdata),
    .RW0_rdata (RW0_rdata)
  );
endmodule

