// Generated by CIRCT firtool-1.74.0
module AXI4UserYanker_3(
  input          clock,
  input          reset,
  output         auto_in_aw_ready,
  input          auto_in_aw_valid,
  input  [36:0]  auto_in_aw_bits_addr,
  input  [7:0]   auto_in_aw_bits_len,
  input  [2:0]   auto_in_aw_bits_size,
  input  [3:0]   auto_in_aw_bits_cache,
  output         auto_in_w_ready,
  input          auto_in_w_valid,
  input  [255:0] auto_in_w_bits_data,
  input  [31:0]  auto_in_w_bits_strb,
  input          auto_in_w_bits_last,
  input          auto_in_b_ready,
  output         auto_in_b_valid,
  output         auto_in_ar_ready,
  input          auto_in_ar_valid,
  input  [36:0]  auto_in_ar_bits_addr,
  input  [7:0]   auto_in_ar_bits_len,
  input  [2:0]   auto_in_ar_bits_size,
  input  [3:0]   auto_in_ar_bits_cache,
  input          auto_in_r_ready,
  output         auto_in_r_valid,
  output [255:0] auto_in_r_bits_data,
  output         auto_in_r_bits_last,
  input          auto_out_aw_ready,
  output         auto_out_aw_valid,
  output [36:0]  auto_out_aw_bits_addr,
  output [7:0]   auto_out_aw_bits_len,
  output [2:0]   auto_out_aw_bits_size,
  output [3:0]   auto_out_aw_bits_cache,
  input          auto_out_w_ready,
  output         auto_out_w_valid,
  output [255:0] auto_out_w_bits_data,
  output [31:0]  auto_out_w_bits_strb,
  output         auto_out_w_bits_last,
  output         auto_out_b_ready,
  input          auto_out_b_valid,
  input  [3:0]   auto_out_b_bits_id,
  input          auto_out_ar_ready,
  output         auto_out_ar_valid,
  output [36:0]  auto_out_ar_bits_addr,
  output [7:0]   auto_out_ar_bits_len,
  output [2:0]   auto_out_ar_bits_size,
  output [3:0]   auto_out_ar_bits_cache,
  output         auto_out_r_ready,
  input          auto_out_r_valid,
  input  [3:0]   auto_out_r_bits_id,
  input  [255:0] auto_out_r_bits_data,
  input          auto_out_r_bits_last
);

  wire _Queue1_BundleMap_16_io_enq_ready;
  wire _Queue1_BundleMap_io_enq_ready;
  Queue1_BundleMap Queue1_BundleMap (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_Queue1_BundleMap_io_enq_ready),
    .io_enq_valid (auto_in_ar_valid & auto_out_ar_ready),
    .io_deq_ready
      (auto_out_r_valid & auto_in_r_ready & auto_out_r_bits_id == 4'h0
       & auto_out_r_bits_last)
  );
  Queue1_BundleMap Queue1_BundleMap_16 (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_Queue1_BundleMap_16_io_enq_ready),
    .io_enq_valid (auto_in_aw_valid & auto_out_aw_ready),
    .io_deq_ready (auto_out_b_valid & auto_in_b_ready & auto_out_b_bits_id == 4'h0)
  );
  assign auto_in_aw_ready = auto_out_aw_ready & _Queue1_BundleMap_16_io_enq_ready;
  assign auto_in_w_ready = auto_out_w_ready;
  assign auto_in_b_valid = auto_out_b_valid;
  assign auto_in_ar_ready = auto_out_ar_ready & _Queue1_BundleMap_io_enq_ready;
  assign auto_in_r_valid = auto_out_r_valid;
  assign auto_in_r_bits_data = auto_out_r_bits_data;
  assign auto_in_r_bits_last = auto_out_r_bits_last;
  assign auto_out_aw_valid = auto_in_aw_valid & _Queue1_BundleMap_16_io_enq_ready;
  assign auto_out_aw_bits_addr = auto_in_aw_bits_addr;
  assign auto_out_aw_bits_len = auto_in_aw_bits_len;
  assign auto_out_aw_bits_size = auto_in_aw_bits_size;
  assign auto_out_aw_bits_cache = auto_in_aw_bits_cache;
  assign auto_out_w_valid = auto_in_w_valid;
  assign auto_out_w_bits_data = auto_in_w_bits_data;
  assign auto_out_w_bits_strb = auto_in_w_bits_strb;
  assign auto_out_w_bits_last = auto_in_w_bits_last;
  assign auto_out_b_ready = auto_in_b_ready;
  assign auto_out_ar_valid = auto_in_ar_valid & _Queue1_BundleMap_io_enq_ready;
  assign auto_out_ar_bits_addr = auto_in_ar_bits_addr;
  assign auto_out_ar_bits_len = auto_in_ar_bits_len;
  assign auto_out_ar_bits_size = auto_in_ar_bits_size;
  assign auto_out_ar_bits_cache = auto_in_ar_bits_cache;
  assign auto_out_r_ready = auto_in_r_ready;
endmodule

