// Generated by CIRCT firtool-1.74.0
module C22(
  input  io_in_0,
  input  io_in_1,
  output io_out_0,
  output io_out_1
);

  assign io_out_0 = io_in_0 ^ io_in_1;
  assign io_out_1 = io_in_0 & io_in_1;
endmodule

