// Generated by CIRCT firtool-1.74.0
module CLZ_10(
  input  [23:0] io_in,
  output [4:0]  io_out
);

  assign io_out =
    io_in[23]
      ? 5'h0
      : io_in[22]
          ? 5'h1
          : io_in[21]
              ? 5'h2
              : io_in[20]
                  ? 5'h3
                  : io_in[19]
                      ? 5'h4
                      : io_in[18]
                          ? 5'h5
                          : io_in[17]
                              ? 5'h6
                              : io_in[16]
                                  ? 5'h7
                                  : io_in[15]
                                      ? 5'h8
                                      : io_in[14]
                                          ? 5'h9
                                          : io_in[13]
                                              ? 5'hA
                                              : io_in[12]
                                                  ? 5'hB
                                                  : io_in[11]
                                                      ? 5'hC
                                                      : io_in[10]
                                                          ? 5'hD
                                                          : io_in[9]
                                                              ? 5'hE
                                                              : io_in[8]
                                                                  ? 5'hF
                                                                  : io_in[7]
                                                                      ? 5'h10
                                                                      : io_in[6]
                                                                          ? 5'h11
                                                                          : io_in[5]
                                                                              ? 5'h12
                                                                              : io_in[4]
                                                                                  ? 5'h13
                                                                                  : io_in[3]
                                                                                      ? 5'h14
                                                                                      : io_in[2]
                                                                                          ? 5'h15
                                                                                          : io_in[1]
                                                                                              ? 5'h16
                                                                                              : io_in[0]
                                                                                                  ? 5'h17
                                                                                                  : 5'h18;
endmodule

