// Generated by CIRCT firtool-1.74.0
// VCS coverage exclude_file
module data_mem_16x12(
  input  [3:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [11:0] R0_data,
  input  [3:0]  R1_addr,
  input         R1_en,
  input         R1_clk,
  output [11:0] R1_data,
  input  [3:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [11:0] W0_data,
  input  [1:0]  W0_mask
);

  reg [11:0] Memory[0:15];
  always @(posedge W0_clk) begin
    if (W0_en & W0_mask[0])
      Memory[W0_addr][32'h0 +: 6] <= W0_data[5:0];
    if (W0_en & W0_mask[1])
      Memory[W0_addr][32'h6 +: 6] <= W0_data[11:6];
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_
    reg [31:0] _RANDOM_MEM;
    initial begin
      `INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_MEM_INIT
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;
          Memory[i[3:0]] = _RANDOM_MEM[11:0];
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 12'bx;
  assign R1_data = R1_en ? Memory[R1_addr] : 12'bx;
endmodule

