// Generated by CIRCT firtool-1.74.0
module Dispatcher_8(
  input         io_in_valid,
  input  [34:0] io_in_bits_fuType,
  input  [8:0]  io_in_bits_fuOpType,
  input  [63:0] io_in_bits_src_0,
  input  [63:0] io_in_bits_src_1,
  input  [63:0] io_in_bits_src_2,
  input         io_in_bits_robIdx_flag,
  input  [7:0]  io_in_bits_robIdx_value,
  input  [7:0]  io_in_bits_pdest,
  input         io_in_bits_rfWen,
  input         io_in_bits_fpWen,
  input         io_in_bits_vecWen,
  input         io_in_bits_v0Wen,
  input         io_in_bits_fpu_wflags,
  input  [2:0]  io_in_bits_fpu_rm,
  input  [1:0]  io_in_bits_vpu_vsew,
  output        io_out_0_valid,
  output [8:0]  io_out_0_bits_fuOpType,
  output [63:0] io_out_0_bits_src_0,
  output [63:0] io_out_0_bits_src_1,
  output        io_out_0_bits_robIdx_flag,
  output [7:0]  io_out_0_bits_robIdx_value,
  output [7:0]  io_out_0_bits_pdest,
  output        io_out_0_bits_rfWen,
  output        io_out_0_bits_fpWen,
  output        io_out_0_bits_fpu_wflags,
  output [2:0]  io_out_0_bits_fpu_rm,
  output [1:0]  io_out_0_bits_vpu_vsew,
  output        io_out_1_valid,
  output [8:0]  io_out_1_bits_fuOpType,
  output [63:0] io_out_1_bits_src_0,
  output        io_out_1_bits_robIdx_flag,
  output [7:0]  io_out_1_bits_robIdx_value,
  output [7:0]  io_out_1_bits_pdest,
  output        io_out_1_bits_rfWen,
  output        io_out_1_bits_fpWen,
  output        io_out_1_bits_fpu_wflags,
  output [2:0]  io_out_1_bits_fpu_rm,
  output [1:0]  io_out_1_bits_vpu_vsew,
  output        io_out_2_valid,
  output [8:0]  io_out_2_bits_fuOpType,
  output [63:0] io_out_2_bits_src_0,
  output [63:0] io_out_2_bits_src_1,
  output        io_out_2_bits_robIdx_flag,
  output [7:0]  io_out_2_bits_robIdx_value,
  output [7:0]  io_out_2_bits_pdest,
  output        io_out_2_bits_vecWen,
  output        io_out_2_bits_v0Wen,
  output        io_out_3_valid,
  output [8:0]  io_out_3_bits_fuOpType,
  output [63:0] io_out_3_bits_src_0,
  output [63:0] io_out_3_bits_src_1,
  output [63:0] io_out_3_bits_src_2,
  output        io_out_3_bits_robIdx_flag,
  output [7:0]  io_out_3_bits_robIdx_value,
  output [7:0]  io_out_3_bits_pdest,
  output        io_out_3_bits_fpWen,
  output        io_out_3_bits_fpu_wflags,
  output [2:0]  io_out_3_bits_fpu_rm,
  output [1:0]  io_out_3_bits_vpu_vsew
);

  assign io_out_0_valid = io_in_bits_fuType == 35'h800 & io_in_valid;
  assign io_out_0_bits_fuOpType = io_in_bits_fuOpType;
  assign io_out_0_bits_src_0 = io_in_bits_src_0;
  assign io_out_0_bits_src_1 = io_in_bits_src_1;
  assign io_out_0_bits_robIdx_flag = io_in_bits_robIdx_flag;
  assign io_out_0_bits_robIdx_value = io_in_bits_robIdx_value;
  assign io_out_0_bits_pdest = io_in_bits_pdest;
  assign io_out_0_bits_rfWen = io_in_bits_rfWen;
  assign io_out_0_bits_fpWen = io_in_bits_fpWen;
  assign io_out_0_bits_fpu_wflags = io_in_bits_fpu_wflags;
  assign io_out_0_bits_fpu_rm = io_in_bits_fpu_rm;
  assign io_out_0_bits_vpu_vsew = io_in_bits_vpu_vsew;
  assign io_out_1_valid = io_in_bits_fuType == 35'h2000 & io_in_valid;
  assign io_out_1_bits_fuOpType = io_in_bits_fuOpType;
  assign io_out_1_bits_src_0 = io_in_bits_src_0;
  assign io_out_1_bits_robIdx_flag = io_in_bits_robIdx_flag;
  assign io_out_1_bits_robIdx_value = io_in_bits_robIdx_value;
  assign io_out_1_bits_pdest = io_in_bits_pdest;
  assign io_out_1_bits_rfWen = io_in_bits_rfWen;
  assign io_out_1_bits_fpWen = io_in_bits_fpWen;
  assign io_out_1_bits_fpu_wflags = io_in_bits_fpu_wflags;
  assign io_out_1_bits_fpu_rm = io_in_bits_fpu_rm;
  assign io_out_1_bits_vpu_vsew = io_in_bits_vpu_vsew;
  assign io_out_2_valid = io_in_bits_fuType == 35'h10 & io_in_valid;
  assign io_out_2_bits_fuOpType = io_in_bits_fuOpType;
  assign io_out_2_bits_src_0 = io_in_bits_src_0;
  assign io_out_2_bits_src_1 = io_in_bits_src_1;
  assign io_out_2_bits_robIdx_flag = io_in_bits_robIdx_flag;
  assign io_out_2_bits_robIdx_value = io_in_bits_robIdx_value;
  assign io_out_2_bits_pdest = io_in_bits_pdest;
  assign io_out_2_bits_vecWen = io_in_bits_vecWen;
  assign io_out_2_bits_v0Wen = io_in_bits_v0Wen;
  assign io_out_3_valid = io_in_bits_fuType == 35'h1000 & io_in_valid;
  assign io_out_3_bits_fuOpType = io_in_bits_fuOpType;
  assign io_out_3_bits_src_0 = io_in_bits_src_0;
  assign io_out_3_bits_src_1 = io_in_bits_src_1;
  assign io_out_3_bits_src_2 = io_in_bits_src_2;
  assign io_out_3_bits_robIdx_flag = io_in_bits_robIdx_flag;
  assign io_out_3_bits_robIdx_value = io_in_bits_robIdx_value;
  assign io_out_3_bits_pdest = io_in_bits_pdest;
  assign io_out_3_bits_fpWen = io_in_bits_fpWen;
  assign io_out_3_bits_fpu_wflags = io_in_bits_fpu_wflags;
  assign io_out_3_bits_fpu_rm = io_in_bits_fpu_rm;
  assign io_out_3_bits_vpu_vsew = io_in_bits_vpu_vsew;
endmodule

