// Generated by CIRCT firtool-1.74.0
module FoldedSRAMTemplate_1(
  input        clock,
  input        reset,
  output       io_r_req_ready,
  input        io_r_req_valid,
  input  [8:0] io_r_req_bits_setIdx,
  output       io_r_resp_data_0_valid,
  output [7:0] io_r_resp_data_0_tag,
  output [2:0] io_r_resp_data_0_ctr,
  output       io_r_resp_data_1_valid,
  output [7:0] io_r_resp_data_1_tag,
  output [2:0] io_r_resp_data_1_ctr,
  input        io_w_req_valid,
  input  [8:0] io_w_req_bits_setIdx,
  input  [7:0] io_w_req_bits_data_0_tag,
  input  [2:0] io_w_req_bits_data_0_ctr,
  input  [7:0] io_w_req_bits_data_1_tag,
  input  [2:0] io_w_req_bits_data_1_ctr,
  input  [1:0] io_w_req_bits_waymask
);

  SRAMTemplate_36 array (
    .clock                    (clock),
    .reset                    (reset),
    .io_r_req_ready           (io_r_req_ready),
    .io_r_req_valid           (io_r_req_valid),
    .io_r_req_bits_setIdx     (io_r_req_bits_setIdx),
    .io_r_resp_data_0_valid   (io_r_resp_data_0_valid),
    .io_r_resp_data_0_tag     (io_r_resp_data_0_tag),
    .io_r_resp_data_0_ctr     (io_r_resp_data_0_ctr),
    .io_r_resp_data_1_valid   (io_r_resp_data_1_valid),
    .io_r_resp_data_1_tag     (io_r_resp_data_1_tag),
    .io_r_resp_data_1_ctr     (io_r_resp_data_1_ctr),
    .io_w_req_valid           (io_w_req_valid),
    .io_w_req_bits_setIdx     (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0_tag (io_w_req_bits_data_0_tag),
    .io_w_req_bits_data_0_ctr (io_w_req_bits_data_0_ctr),
    .io_w_req_bits_data_1_tag (io_w_req_bits_data_1_tag),
    .io_w_req_bits_data_1_ctr (io_w_req_bits_data_1_ctr),
    .io_w_req_bits_waymask    (io_w_req_bits_waymask)
  );
endmodule

