// Generated by CIRCT firtool-1.74.0
module FuBusyTableRead_77(
  input  [4:0]  io_in_fuBusyTable,
  input  [34:0] io_in_fuTypeRegVec_0,
  input  [34:0] io_in_fuTypeRegVec_1,
  input  [34:0] io_in_fuTypeRegVec_2,
  input  [34:0] io_in_fuTypeRegVec_3,
  input  [34:0] io_in_fuTypeRegVec_4,
  input  [34:0] io_in_fuTypeRegVec_5,
  input  [34:0] io_in_fuTypeRegVec_6,
  input  [34:0] io_in_fuTypeRegVec_7,
  input  [34:0] io_in_fuTypeRegVec_8,
  input  [34:0] io_in_fuTypeRegVec_9,
  input  [34:0] io_in_fuTypeRegVec_10,
  input  [34:0] io_in_fuTypeRegVec_11,
  input  [34:0] io_in_fuTypeRegVec_12,
  input  [34:0] io_in_fuTypeRegVec_13,
  input  [34:0] io_in_fuTypeRegVec_14,
  input  [34:0] io_in_fuTypeRegVec_15,
  output [15:0] io_out_fuBusyTableMask
);

  assign io_out_fuBusyTableMask =
    (io_in_fuBusyTable[2]
       ? {io_in_fuTypeRegVec_15[30],
          io_in_fuTypeRegVec_14[30],
          io_in_fuTypeRegVec_13[30],
          io_in_fuTypeRegVec_12[30],
          io_in_fuTypeRegVec_11[30],
          io_in_fuTypeRegVec_10[30],
          io_in_fuTypeRegVec_9[30],
          io_in_fuTypeRegVec_8[30],
          io_in_fuTypeRegVec_7[30],
          io_in_fuTypeRegVec_6[30],
          io_in_fuTypeRegVec_5[30],
          io_in_fuTypeRegVec_4[30],
          io_in_fuTypeRegVec_3[30],
          io_in_fuTypeRegVec_2[30],
          io_in_fuTypeRegVec_1[30],
          io_in_fuTypeRegVec_0[30]}
       : 16'h0)
    | (io_in_fuBusyTable[4]
         ? {io_in_fuTypeRegVec_15[18],
            io_in_fuTypeRegVec_14[18],
            io_in_fuTypeRegVec_13[18],
            io_in_fuTypeRegVec_12[18],
            io_in_fuTypeRegVec_11[18],
            io_in_fuTypeRegVec_10[18],
            io_in_fuTypeRegVec_9[18],
            io_in_fuTypeRegVec_8[18],
            io_in_fuTypeRegVec_7[18],
            io_in_fuTypeRegVec_6[18],
            io_in_fuTypeRegVec_5[18],
            io_in_fuTypeRegVec_4[18],
            io_in_fuTypeRegVec_3[18],
            io_in_fuTypeRegVec_2[18],
            io_in_fuTypeRegVec_1[18],
            io_in_fuTypeRegVec_0[18]}
         : 16'h0);
endmodule

