// Generated by CIRCT firtool-1.74.0
module ImmExtractor_10(
  input  [31:0]  io_in_imm,
  input  [3:0]   io_in_immType,
  output [127:0] io_out_imm
);

  assign io_out_imm =
    {64'h0,
     (&io_in_immType)
       ? {58'h0, io_in_imm[5:0]}
       : io_in_immType == 4'hD
           ? {{49{io_in_imm[14]}}, io_in_imm[14:0]}
           : io_in_immType == 4'hC
               ? {{53{io_in_imm[10]}}, io_in_imm[10:0]}
               : io_in_immType == 4'hA
                   ? {59'h0, io_in_imm[4:0]}
                   : io_in_immType == 4'h9
                       ? {{59{io_in_imm[4]}}, io_in_imm[4:0]}
                       : io_in_immType == 4'h4
                           ? {{52{io_in_imm[11]}}, io_in_imm[11:0]}
                           : io_in_immType == 4'h3
                               ? {{43{io_in_imm[19]}}, io_in_imm[19:0], 1'h0}
                               : io_in_immType == 4'h2
                                   ? {{32{io_in_imm[19]}}, io_in_imm[19:0], 12'h0}
                                   : io_in_immType == 4'h1
                                       ? {{51{io_in_imm[11]}}, io_in_imm[11:0], 1'h0}
                                       : 64'h0};
endmodule

