// Generated by CIRCT firtool-1.74.0
module ImmExtractor_37(
  input  [31:0]  io_in_imm,
  input  [3:0]   io_in_immType,
  output [127:0] io_out_imm
);

  assign io_out_imm =
    {64'h0,
     io_in_immType == 4'hD
       ? {{49{io_in_imm[14]}}, io_in_imm[14:0]}
       : io_in_immType == 4'hC ? {{53{io_in_imm[10]}}, io_in_imm[10:0]} : 64'h0};
endmodule

