// Generated by CIRCT firtool-1.74.0
// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS
// Standard header to adapt well known macros for register randomization.
// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM
// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM
// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY
// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module InterruptFilter(
  input          clock,
  input          reset,
  input  [1:0]   io_in_privState_PRVM,
  input          io_in_privState_V,
  input          io_in_mstatusMIE,
  input          io_in_sstatusSIE,
  input          io_in_vsstatusSIE,
  input  [63:0]  io_in_mip,
  input  [63:0]  io_in_mie,
  input  [63:0]  io_in_mideleg,
  input  [63:0]  io_in_sip,
  input  [63:0]  io_in_sie,
  input  [63:0]  io_in_hip,
  input  [63:0]  io_in_hie,
  input  [63:0]  io_in_hideleg,
  input  [63:0]  io_in_vsip,
  input  [63:0]  io_in_vsie,
  input          io_in_hvictl_VTI,
  input  [11:0]  io_in_hvictl_IID,
  input          io_in_hvictl_DPR,
  input          io_in_hvictl_IPRIOM,
  input  [7:0]   io_in_hvictl_IPRIO,
  input  [5:0]   io_in_hstatus_VGEIN,
  input  [10:0]  io_in_vstopei_IID,
  input  [10:0]  io_in_vstopei_IPRIO,
  input  [7:0]   io_in_hviprio1_PrioSSI,
  input  [7:0]   io_in_hviprio1_PrioSTI,
  input  [7:0]   io_in_hviprio1_PrioCOI,
  input  [7:0]   io_in_hviprio1_Prio14,
  input  [7:0]   io_in_hviprio1_Prio15,
  input          io_in_debugIntr,
  input          io_in_debugMode,
  input          io_in_dcsr_STEPIE,
  input          io_in_dcsr_STEP,
  input  [511:0] io_in_miprios,
  input  [511:0] io_in_hsiprios,
  output         io_out_interruptVec_valid,
  output [63:0]  io_out_interruptVec_bits,
  output [11:0]  io_out_mtopi_IID,
  output [7:0]   io_out_mtopi_IPRIO,
  output [11:0]  io_out_stopi_IID,
  output [7:0]   io_out_stopi_IPRIO,
  output [11:0]  io_out_vstopi_IID,
  output [7:0]   io_out_vstopi_IPRIO
);

  wire [63:0] _delayedIntrVec_delay_io_out;
  wire        mIRVec_v_PrvmIsM_1 = 1'h1;
  wire        PrvmIsS_2 = 1'h1;
  wire        PrvmIsS_3 = 1'h1;
  wire        PrvmIsS_1 = 1'h0;
  wire        hsIRVec_v_PrvmIsM = 1'h0;
  wire        vsIRVec_v_PrvmIsM = 1'h0;
  wire        vsIRVec_isModeHS = 1'h0;
  wire [63:0] hsip = io_in_hip | io_in_sip;
  wire [63:0] hsie = io_in_hie | io_in_sie;
  wire [63:0] mtopigather = io_in_mip & io_in_mie;
  wire [63:0] _mtopiIsNotZero_T_2 = mtopigather & ~io_in_mideleg;
  wire        PrvmIsS = io_in_privState_PRVM == 2'h1;
  wire        stopiIsNotZero_isModeHS = ~io_in_privState_V & PrvmIsS;
  wire [63:0] hstopigather = hsip & hsie;
  wire        stopiIsNotZero =
    stopiIsNotZero_isModeHS & (|(hstopigather & ~io_in_hideleg));
  wire        _mipriosSort_0_T = io_in_mip[43] & io_in_mie[43];
  wire [8:0]  _mipriosSort_0_T_2 = {1'h1, io_in_miprios[351:344]};
  wire [8:0]  mipriosSort_0 = _mipriosSort_0_T ? _mipriosSort_0_T_2 : 9'h0;
  wire        _hsipriosSort_0_T = hsip[43] & hsie[43];
  wire [8:0]  _hsipriosSort_0_T_2 = {1'h1, io_in_hsiprios[351:344]};
  wire [8:0]  hsipriosSort_0 = _hsipriosSort_0_T ? _hsipriosSort_0_T_2 : 9'h0;
  wire        _mipriosSort_1_T = io_in_mip[11] & io_in_mie[11];
  wire [8:0]  _mipriosSort_1_T_2 = {1'h1, io_in_miprios[95:88]};
  wire [8:0]  mipriosSort_1 = _mipriosSort_1_T ? _mipriosSort_1_T_2 : 9'h0;
  wire        _hsipriosSort_1_T = hsip[11] & hsie[11];
  wire [8:0]  _hsipriosSort_1_T_2 = {1'h1, io_in_hsiprios[95:88]};
  wire [8:0]  hsipriosSort_1 = _hsipriosSort_1_T ? _hsipriosSort_1_T_2 : 9'h0;
  wire        _mipriosSort_2_T = io_in_mip[3] & io_in_mie[3];
  wire [8:0]  _mipriosSort_2_T_2 = {1'h1, io_in_miprios[31:24]};
  wire [8:0]  mipriosSort_2 = _mipriosSort_2_T ? _mipriosSort_2_T_2 : 9'h0;
  wire        _hsipriosSort_2_T = hsip[3] & hsie[3];
  wire [8:0]  _hsipriosSort_2_T_2 = {1'h1, io_in_hsiprios[31:24]};
  wire [8:0]  hsipriosSort_2 = _hsipriosSort_2_T ? _hsipriosSort_2_T_2 : 9'h0;
  wire        _mipriosSort_3_T = io_in_mip[7] & io_in_mie[7];
  wire [8:0]  _mipriosSort_3_T_2 = {1'h1, io_in_miprios[63:56]};
  wire [8:0]  mipriosSort_3 = _mipriosSort_3_T ? _mipriosSort_3_T_2 : 9'h0;
  wire        _hsipriosSort_3_T = hsip[7] & hsie[7];
  wire [8:0]  _hsipriosSort_3_T_2 = {1'h1, io_in_hsiprios[63:56]};
  wire [8:0]  hsipriosSort_3 = _hsipriosSort_3_T ? _hsipriosSort_3_T_2 : 9'h0;
  wire        _mipriosSort_4_T = io_in_mip[9] & io_in_mie[9];
  wire [8:0]  _mipriosSort_4_T_2 = {1'h1, io_in_miprios[79:72]};
  wire [8:0]  mipriosSort_4 = _mipriosSort_4_T ? _mipriosSort_4_T_2 : 9'h0;
  wire        _hsipriosSort_4_T = hsip[9] & hsie[9];
  wire [8:0]  _hsipriosSort_4_T_2 = {1'h1, io_in_hsiprios[79:72]};
  wire [8:0]  hsipriosSort_4 = _hsipriosSort_4_T ? _hsipriosSort_4_T_2 : 9'h0;
  wire        _mipriosSort_5_T = io_in_mip[1] & io_in_mie[1];
  wire [8:0]  _mipriosSort_5_T_2 = {1'h1, io_in_miprios[15:8]};
  wire [8:0]  mipriosSort_5 = _mipriosSort_5_T ? _mipriosSort_5_T_2 : 9'h0;
  wire        _hsipriosSort_5_T = hsip[1] & hsie[1];
  wire [8:0]  _hsipriosSort_5_T_2 = {1'h1, io_in_hsiprios[15:8]};
  wire [8:0]  hsipriosSort_5 = _hsipriosSort_5_T ? _hsipriosSort_5_T_2 : 9'h0;
  wire        _mipriosSort_6_T = io_in_mip[5] & io_in_mie[5];
  wire [8:0]  _mipriosSort_6_T_2 = {1'h1, io_in_miprios[47:40]};
  wire [8:0]  mipriosSort_6 = _mipriosSort_6_T ? _mipriosSort_6_T_2 : 9'h0;
  wire        _hsipriosSort_6_T = hsip[5] & hsie[5];
  wire [8:0]  _hsipriosSort_6_T_2 = {1'h1, io_in_hsiprios[47:40]};
  wire [8:0]  hsipriosSort_6 = _hsipriosSort_6_T ? _hsipriosSort_6_T_2 : 9'h0;
  wire        _mipriosSort_7_T = io_in_mip[12] & io_in_mie[12];
  wire [8:0]  _mipriosSort_7_T_2 = {1'h1, io_in_miprios[103:96]};
  wire [8:0]  mipriosSort_7 = _mipriosSort_7_T ? _mipriosSort_7_T_2 : 9'h0;
  wire        _hsipriosSort_7_T = hsip[12] & hsie[12];
  wire [8:0]  _hsipriosSort_7_T_2 = {1'h1, io_in_hsiprios[103:96]};
  wire [8:0]  hsipriosSort_7 = _hsipriosSort_7_T ? _hsipriosSort_7_T_2 : 9'h0;
  wire        _mipriosSort_8_T = io_in_mip[10] & io_in_mie[10];
  wire [8:0]  _mipriosSort_8_T_2 = {1'h1, io_in_miprios[87:80]};
  wire [8:0]  mipriosSort_8 = _mipriosSort_8_T ? _mipriosSort_8_T_2 : 9'h0;
  wire        _hsipriosSort_8_T = hsip[10] & hsie[10];
  wire [8:0]  _hsipriosSort_8_T_2 = {1'h1, io_in_hsiprios[87:80]};
  wire [8:0]  hsipriosSort_8 = _hsipriosSort_8_T ? _hsipriosSort_8_T_2 : 9'h0;
  wire        _mipriosSort_9_T = io_in_mip[2] & io_in_mie[2];
  wire [8:0]  _mipriosSort_9_T_2 = {1'h1, io_in_miprios[23:16]};
  wire [8:0]  mipriosSort_9 = _mipriosSort_9_T ? _mipriosSort_9_T_2 : 9'h0;
  wire        _hsipriosSort_9_T = hsip[2] & hsie[2];
  wire [8:0]  _hsipriosSort_9_T_2 = {1'h1, io_in_hsiprios[23:16]};
  wire [8:0]  hsipriosSort_9 = _hsipriosSort_9_T ? _hsipriosSort_9_T_2 : 9'h0;
  wire        _mipriosSort_10_T = io_in_mip[6] & io_in_mie[6];
  wire [8:0]  _mipriosSort_10_T_2 = {1'h1, io_in_miprios[55:48]};
  wire [8:0]  mipriosSort_10 = _mipriosSort_10_T ? _mipriosSort_10_T_2 : 9'h0;
  wire        _hsipriosSort_10_T = hsip[6] & hsie[6];
  wire [8:0]  _hsipriosSort_10_T_2 = {1'h1, io_in_hsiprios[55:48]};
  wire [8:0]  hsipriosSort_10 = _hsipriosSort_10_T ? _hsipriosSort_10_T_2 : 9'h0;
  wire        _mipriosSort_11_T = io_in_mip[13] & io_in_mie[13];
  wire [8:0]  _mipriosSort_11_T_2 = {1'h1, io_in_miprios[111:104]};
  wire [8:0]  mipriosSort_11 = _mipriosSort_11_T ? _mipriosSort_11_T_2 : 9'h0;
  wire        _hsipriosSort_11_T = hsip[13] & hsie[13];
  wire [8:0]  _hsipriosSort_11_T_2 = {1'h1, io_in_hsiprios[111:104]};
  wire [8:0]  hsipriosSort_11 = _hsipriosSort_11_T ? _hsipriosSort_11_T_2 : 9'h0;
  wire        _mipriosSort_12_T = io_in_mip[35] & io_in_mie[35];
  wire [8:0]  _mipriosSort_12_T_2 = {1'h1, io_in_miprios[287:280]};
  wire [8:0]  mipriosSort_12 = _mipriosSort_12_T ? _mipriosSort_12_T_2 : 9'h0;
  wire        _hsipriosSort_12_T = hsip[35] & hsie[35];
  wire [8:0]  _hsipriosSort_12_T_2 = {1'h1, io_in_hsiprios[287:280]};
  wire [8:0]  hsipriosSort_12 = _hsipriosSort_12_T ? _hsipriosSort_12_T_2 : 9'h0;
  wire        _hvipriosSort_0_T = io_in_vsip[1] & io_in_vsie[1];
  wire [8:0]  _hvipriosSort_0_T_2 = {1'h1, io_in_hviprio1_PrioSSI};
  wire [8:0]  hvipriosSort_0 = _hvipriosSort_0_T ? _hvipriosSort_0_T_2 : 9'h0;
  wire        _hvipriosSort_1_T = io_in_vsip[5] & io_in_vsie[5];
  wire [8:0]  _hvipriosSort_1_T_2 = {1'h1, io_in_hviprio1_PrioSTI};
  wire [8:0]  hvipriosSort_1 = _hvipriosSort_1_T ? _hvipriosSort_1_T_2 : 9'h0;
  wire        _hvipriosSort_2_T = io_in_vsip[13] & io_in_vsie[13];
  wire [8:0]  hvipriosSort_2 = _hvipriosSort_2_T ? {1'h1, io_in_hviprio1_PrioCOI} : 9'h0;
  wire [5:0]  result_minIndex =
    {5'h0,
     mipriosSort_1[8]
       & (mipriosSort_0[8] & mipriosSort_0[7:0] > mipriosSort_1[7:0]
          | ~(mipriosSort_0[8]))};
  wire [8:0]  result_minValue =
    (mipriosSort_0[8]
     & (mipriosSort_1[8] & mipriosSort_0[7:0] < mipriosSort_1[7:0] | ~(mipriosSort_1[8]))
     & _mipriosSort_0_T
       ? _mipriosSort_0_T_2
       : 9'h0)
    | (mipriosSort_1[8]
       & (mipriosSort_0[8] & mipriosSort_0[7:0] > mipriosSort_1[7:0]
          | ~(mipriosSort_0[8])) & _mipriosSort_1_T
         ? _mipriosSort_1_T_2
         : 9'h0)
    | (mipriosSort_0[8] & mipriosSort_1[8] & mipriosSort_0[7:0] == mipriosSort_1[7:0]
       & _mipriosSort_0_T
         ? _mipriosSort_0_T_2
         : 9'h0);
  wire [5:0]  result_minIndex_1 =
    (mipriosSort_3[8]
     & (mipriosSort_2[8] & mipriosSort_2[7:0] > mipriosSort_3[7:0] | ~(mipriosSort_2[8]))
       ? 6'h3
       : 6'h0)
    | {4'h0,
       mipriosSort_2[8]
         & (mipriosSort_3[8] & mipriosSort_2[7:0] < mipriosSort_3[7:0]
            | ~(mipriosSort_3[8])) | mipriosSort_2[8] & mipriosSort_3[8]
         & mipriosSort_2[7:0] == mipriosSort_3[7:0],
       1'h0};
  wire [8:0]  result_minValue_1 =
    (mipriosSort_2[8]
     & (mipriosSort_3[8] & mipriosSort_2[7:0] < mipriosSort_3[7:0] | ~(mipriosSort_3[8]))
     & _mipriosSort_2_T
       ? _mipriosSort_2_T_2
       : 9'h0)
    | (mipriosSort_3[8]
       & (mipriosSort_2[8] & mipriosSort_2[7:0] > mipriosSort_3[7:0]
          | ~(mipriosSort_2[8])) & _mipriosSort_3_T
         ? _mipriosSort_3_T_2
         : 9'h0)
    | (mipriosSort_2[8] & mipriosSort_3[8] & mipriosSort_2[7:0] == mipriosSort_3[7:0]
       & _mipriosSort_2_T
         ? _mipriosSort_2_T_2
         : 9'h0);
  wire        _result_minValue_T_95 = result_minIndex < result_minIndex_1;
  wire [5:0]  result_minIndex_2 =
    (result_minValue[8]
     & (result_minValue_1[8] & result_minValue[7:0] < result_minValue_1[7:0]
        | ~(result_minValue_1[8]))
       ? result_minIndex
       : 6'h0)
    | (result_minValue_1[8]
       & (result_minValue[8] & result_minValue[7:0] > result_minValue_1[7:0]
          | ~(result_minValue[8]))
         ? result_minIndex_1
         : 6'h0)
    | (result_minValue[8] & result_minValue_1[8]
       & result_minValue[7:0] == result_minValue_1[7:0]
         ? (_result_minValue_T_95 ? result_minIndex : result_minIndex_1)
         : 6'h0);
  wire [8:0]  result_minValue_2 =
    (result_minValue[8]
     & (result_minValue_1[8] & result_minValue[7:0] < result_minValue_1[7:0]
        | ~(result_minValue_1[8]))
       ? result_minValue
       : 9'h0)
    | (result_minValue_1[8]
       & (result_minValue[8] & result_minValue[7:0] > result_minValue_1[7:0]
          | ~(result_minValue[8]))
         ? result_minValue_1
         : 9'h0)
    | (result_minValue[8] & result_minValue_1[8]
       & result_minValue[7:0] == result_minValue_1[7:0]
         ? (_result_minValue_T_95 ? result_minValue : result_minValue_1)
         : 9'h0);
  wire [5:0]  result_minIndex_3 =
    (mipriosSort_5[8]
     & (mipriosSort_4[8] & mipriosSort_4[7:0] > mipriosSort_5[7:0] | ~(mipriosSort_4[8]))
       ? 6'h5
       : 6'h0)
    | {3'h0,
       mipriosSort_4[8]
         & (mipriosSort_5[8] & mipriosSort_4[7:0] < mipriosSort_5[7:0]
            | ~(mipriosSort_5[8])) | mipriosSort_4[8] & mipriosSort_5[8]
         & mipriosSort_4[7:0] == mipriosSort_5[7:0],
       2'h0};
  wire [8:0]  result_minValue_3 =
    (mipriosSort_4[8]
     & (mipriosSort_5[8] & mipriosSort_4[7:0] < mipriosSort_5[7:0] | ~(mipriosSort_5[8]))
     & _mipriosSort_4_T
       ? _mipriosSort_4_T_2
       : 9'h0)
    | (mipriosSort_5[8]
       & (mipriosSort_4[8] & mipriosSort_4[7:0] > mipriosSort_5[7:0]
          | ~(mipriosSort_4[8])) & _mipriosSort_5_T
         ? _mipriosSort_5_T_2
         : 9'h0)
    | (mipriosSort_4[8] & mipriosSort_5[8] & mipriosSort_4[7:0] == mipriosSort_5[7:0]
       & _mipriosSort_4_T
         ? _mipriosSort_4_T_2
         : 9'h0);
  wire        _result_minValue_T_163 = result_minIndex_3 < 6'h6;
  wire [5:0]  result_minIndex_4 =
    (result_minValue_3[8]
     & (mipriosSort_6[8] & result_minValue_3[7:0] < mipriosSort_6[7:0]
        | ~(mipriosSort_6[8]))
       ? result_minIndex_3
       : 6'h0)
    | (mipriosSort_6[8]
       & (result_minValue_3[8] & result_minValue_3[7:0] > mipriosSort_6[7:0]
          | ~(result_minValue_3[8]))
         ? 6'h6
         : 6'h0)
    | (result_minValue_3[8] & mipriosSort_6[8]
       & result_minValue_3[7:0] == mipriosSort_6[7:0]
         ? (_result_minValue_T_163 ? result_minIndex_3 : 6'h6)
         : 6'h0);
  wire [8:0]  result_minValue_4 =
    (result_minValue_3[8]
     & (mipriosSort_6[8] & result_minValue_3[7:0] < mipriosSort_6[7:0]
        | ~(mipriosSort_6[8]))
       ? result_minValue_3
       : 9'h0)
    | (mipriosSort_6[8]
       & (result_minValue_3[8] & result_minValue_3[7:0] > mipriosSort_6[7:0]
          | ~(result_minValue_3[8])) & _mipriosSort_6_T
         ? _mipriosSort_6_T_2
         : 9'h0)
    | (result_minValue_3[8] & mipriosSort_6[8]
       & result_minValue_3[7:0] == mipriosSort_6[7:0]
         ? (_result_minValue_T_163 ? result_minValue_3 : mipriosSort_6)
         : 9'h0);
  wire        _result_minValue_T_197 = result_minIndex_2 < result_minIndex_4;
  wire [5:0]  result_minIndex_5 =
    (result_minValue_2[8]
     & (result_minValue_4[8] & result_minValue_2[7:0] < result_minValue_4[7:0]
        | ~(result_minValue_4[8]))
       ? result_minIndex_2
       : 6'h0)
    | (result_minValue_4[8]
       & (result_minValue_2[8] & result_minValue_2[7:0] > result_minValue_4[7:0]
          | ~(result_minValue_2[8]))
         ? result_minIndex_4
         : 6'h0)
    | (result_minValue_2[8] & result_minValue_4[8]
       & result_minValue_2[7:0] == result_minValue_4[7:0]
         ? (_result_minValue_T_197 ? result_minIndex_2 : result_minIndex_4)
         : 6'h0);
  wire [8:0]  result_minValue_5 =
    (result_minValue_2[8]
     & (result_minValue_4[8] & result_minValue_2[7:0] < result_minValue_4[7:0]
        | ~(result_minValue_4[8]))
       ? result_minValue_2
       : 9'h0)
    | (result_minValue_4[8]
       & (result_minValue_2[8] & result_minValue_2[7:0] > result_minValue_4[7:0]
          | ~(result_minValue_2[8]))
         ? result_minValue_4
         : 9'h0)
    | (result_minValue_2[8] & result_minValue_4[8]
       & result_minValue_2[7:0] == result_minValue_4[7:0]
         ? (_result_minValue_T_197 ? result_minValue_2 : result_minValue_4)
         : 9'h0);
  wire [5:0]  result_minIndex_6 =
    (mipriosSort_7[8]
     & (mipriosSort_8[8] & mipriosSort_7[7:0] < mipriosSort_8[7:0] | ~(mipriosSort_8[8]))
       ? 6'h7
       : 6'h0)
    | {2'h0,
       mipriosSort_8[8]
         & (mipriosSort_7[8] & mipriosSort_7[7:0] > mipriosSort_8[7:0]
            | ~(mipriosSort_7[8])),
       3'h0}
    | (mipriosSort_7[8] & mipriosSort_8[8] & mipriosSort_7[7:0] == mipriosSort_8[7:0]
         ? 6'h7
         : 6'h0);
  wire [8:0]  result_minValue_6 =
    (mipriosSort_7[8]
     & (mipriosSort_8[8] & mipriosSort_7[7:0] < mipriosSort_8[7:0] | ~(mipriosSort_8[8]))
     & _mipriosSort_7_T
       ? _mipriosSort_7_T_2
       : 9'h0)
    | (mipriosSort_8[8]
       & (mipriosSort_7[8] & mipriosSort_7[7:0] > mipriosSort_8[7:0]
          | ~(mipriosSort_7[8])) & _mipriosSort_8_T
         ? _mipriosSort_8_T_2
         : 9'h0)
    | (mipriosSort_7[8] & mipriosSort_8[8] & mipriosSort_7[7:0] == mipriosSort_8[7:0]
       & _mipriosSort_7_T
         ? _mipriosSort_7_T_2
         : 9'h0);
  wire        _result_minValue_T_265 = result_minIndex_6 < 6'h9;
  wire [5:0]  result_minIndex_7 =
    (result_minValue_6[8]
     & (mipriosSort_9[8] & result_minValue_6[7:0] < mipriosSort_9[7:0]
        | ~(mipriosSort_9[8]))
       ? result_minIndex_6
       : 6'h0)
    | (mipriosSort_9[8]
       & (result_minValue_6[8] & result_minValue_6[7:0] > mipriosSort_9[7:0]
          | ~(result_minValue_6[8]))
         ? 6'h9
         : 6'h0)
    | (result_minValue_6[8] & mipriosSort_9[8]
       & result_minValue_6[7:0] == mipriosSort_9[7:0]
         ? (_result_minValue_T_265 ? result_minIndex_6 : 6'h9)
         : 6'h0);
  wire [8:0]  result_minValue_7 =
    (result_minValue_6[8]
     & (mipriosSort_9[8] & result_minValue_6[7:0] < mipriosSort_9[7:0]
        | ~(mipriosSort_9[8]))
       ? result_minValue_6
       : 9'h0)
    | (mipriosSort_9[8]
       & (result_minValue_6[8] & result_minValue_6[7:0] > mipriosSort_9[7:0]
          | ~(result_minValue_6[8])) & _mipriosSort_9_T
         ? _mipriosSort_9_T_2
         : 9'h0)
    | (result_minValue_6[8] & mipriosSort_9[8]
       & result_minValue_6[7:0] == mipriosSort_9[7:0]
         ? (_result_minValue_T_265 ? result_minValue_6 : mipriosSort_9)
         : 9'h0);
  wire [5:0]  result_minIndex_8 =
    (mipriosSort_10[8]
     & (mipriosSort_11[8] & mipriosSort_10[7:0] < mipriosSort_11[7:0]
        | ~(mipriosSort_11[8]))
       ? 6'hA
       : 6'h0)
    | (mipriosSort_11[8]
       & (mipriosSort_10[8] & mipriosSort_10[7:0] > mipriosSort_11[7:0]
          | ~(mipriosSort_10[8]))
         ? 6'hB
         : 6'h0)
    | (mipriosSort_10[8] & mipriosSort_11[8] & mipriosSort_10[7:0] == mipriosSort_11[7:0]
         ? 6'hA
         : 6'h0);
  wire [8:0]  result_minValue_8 =
    (mipriosSort_10[8]
     & (mipriosSort_11[8] & mipriosSort_10[7:0] < mipriosSort_11[7:0]
        | ~(mipriosSort_11[8])) & _mipriosSort_10_T
       ? _mipriosSort_10_T_2
       : 9'h0)
    | (mipriosSort_11[8]
       & (mipriosSort_10[8] & mipriosSort_10[7:0] > mipriosSort_11[7:0]
          | ~(mipriosSort_10[8])) & _mipriosSort_11_T
         ? _mipriosSort_11_T_2
         : 9'h0)
    | (mipriosSort_10[8] & mipriosSort_11[8] & mipriosSort_10[7:0] == mipriosSort_11[7:0]
       & _mipriosSort_10_T
         ? _mipriosSort_10_T_2
         : 9'h0);
  wire        _result_minValue_T_333 = result_minIndex_8 < 6'hC;
  wire [5:0]  result_minIndex_9 =
    (result_minValue_8[8]
     & (mipriosSort_12[8] & result_minValue_8[7:0] < mipriosSort_12[7:0]
        | ~(mipriosSort_12[8]))
       ? result_minIndex_8
       : 6'h0)
    | (mipriosSort_12[8]
       & (result_minValue_8[8] & result_minValue_8[7:0] > mipriosSort_12[7:0]
          | ~(result_minValue_8[8]))
         ? 6'hC
         : 6'h0)
    | (result_minValue_8[8] & mipriosSort_12[8]
       & result_minValue_8[7:0] == mipriosSort_12[7:0]
         ? (_result_minValue_T_333 ? result_minIndex_8 : 6'hC)
         : 6'h0);
  wire [8:0]  result_minValue_9 =
    (result_minValue_8[8]
     & (mipriosSort_12[8] & result_minValue_8[7:0] < mipriosSort_12[7:0]
        | ~(mipriosSort_12[8]))
       ? result_minValue_8
       : 9'h0)
    | (mipriosSort_12[8]
       & (result_minValue_8[8] & result_minValue_8[7:0] > mipriosSort_12[7:0]
          | ~(result_minValue_8[8])) & _mipriosSort_12_T
         ? _mipriosSort_12_T_2
         : 9'h0)
    | (result_minValue_8[8] & mipriosSort_12[8]
       & result_minValue_8[7:0] == mipriosSort_12[7:0]
         ? (_result_minValue_T_333 ? result_minValue_8 : mipriosSort_12)
         : 9'h0);
  wire        _result_minValue_T_367 = result_minIndex_7 < result_minIndex_9;
  wire [5:0]  result_minIndex_10 =
    (result_minValue_7[8]
     & (result_minValue_9[8] & result_minValue_7[7:0] < result_minValue_9[7:0]
        | ~(result_minValue_9[8]))
       ? result_minIndex_7
       : 6'h0)
    | (result_minValue_9[8]
       & (result_minValue_7[8] & result_minValue_7[7:0] > result_minValue_9[7:0]
          | ~(result_minValue_7[8]))
         ? result_minIndex_9
         : 6'h0)
    | (result_minValue_7[8] & result_minValue_9[8]
       & result_minValue_7[7:0] == result_minValue_9[7:0]
         ? (_result_minValue_T_367 ? result_minIndex_7 : result_minIndex_9)
         : 6'h0);
  wire [8:0]  result_minValue_10 =
    (result_minValue_7[8]
     & (result_minValue_9[8] & result_minValue_7[7:0] < result_minValue_9[7:0]
        | ~(result_minValue_9[8]))
       ? result_minValue_7
       : 9'h0)
    | (result_minValue_9[8]
       & (result_minValue_7[8] & result_minValue_7[7:0] > result_minValue_9[7:0]
          | ~(result_minValue_7[8]))
         ? result_minValue_9
         : 9'h0)
    | (result_minValue_7[8] & result_minValue_9[8]
       & result_minValue_7[7:0] == result_minValue_9[7:0]
         ? (_result_minValue_T_367 ? result_minValue_7 : result_minValue_9)
         : 9'h0);
  wire        _result_minValue_T_401 = result_minIndex_5 < result_minIndex_10;
  wire [5:0]  result_1_0 =
    (result_minValue_5[8]
     & (result_minValue_10[8] & result_minValue_5[7:0] < result_minValue_10[7:0]
        | ~(result_minValue_10[8]))
       ? result_minIndex_5
       : 6'h0)
    | (result_minValue_10[8]
       & (result_minValue_5[8] & result_minValue_5[7:0] > result_minValue_10[7:0]
          | ~(result_minValue_5[8]))
         ? result_minIndex_10
         : 6'h0)
    | (result_minValue_5[8] & result_minValue_10[8]
       & result_minValue_5[7:0] == result_minValue_10[7:0]
         ? (_result_minValue_T_401 ? result_minIndex_5 : result_minIndex_10)
         : 6'h0);
  wire [7:0]  result_2_0 =
    (result_minValue_5[8]
     & (result_minValue_10[8] & result_minValue_5[7:0] < result_minValue_10[7:0]
        | ~(result_minValue_10[8]))
       ? result_minValue_5[7:0]
       : 8'h0)
    | (result_minValue_10[8]
       & (result_minValue_5[8] & result_minValue_5[7:0] > result_minValue_10[7:0]
          | ~(result_minValue_5[8]))
         ? result_minValue_10[7:0]
         : 8'h0)
    | (result_minValue_5[8] & result_minValue_10[8]
       & result_minValue_5[7:0] == result_minValue_10[7:0]
         ? (_result_minValue_T_401 ? result_minValue_5[7:0] : result_minValue_10[7:0])
         : 8'h0);
  wire [5:0]  result_minIndex_12 =
    {5'h0,
     hsipriosSort_1[8]
       & (hsipriosSort_0[8] & hsipriosSort_0[7:0] > hsipriosSort_1[7:0]
          | ~(hsipriosSort_0[8]))};
  wire [8:0]  result_minValue_12 =
    (hsipriosSort_0[8]
     & (hsipriosSort_1[8] & hsipriosSort_0[7:0] < hsipriosSort_1[7:0]
        | ~(hsipriosSort_1[8])) & _hsipriosSort_0_T
       ? _hsipriosSort_0_T_2
       : 9'h0)
    | (hsipriosSort_1[8]
       & (hsipriosSort_0[8] & hsipriosSort_0[7:0] > hsipriosSort_1[7:0]
          | ~(hsipriosSort_0[8])) & _hsipriosSort_1_T
         ? _hsipriosSort_1_T_2
         : 9'h0)
    | (hsipriosSort_0[8] & hsipriosSort_1[8] & hsipriosSort_0[7:0] == hsipriosSort_1[7:0]
       & _hsipriosSort_0_T
         ? _hsipriosSort_0_T_2
         : 9'h0);
  wire [5:0]  result_minIndex_13 =
    (hsipriosSort_3[8]
     & (hsipriosSort_2[8] & hsipriosSort_2[7:0] > hsipriosSort_3[7:0]
        | ~(hsipriosSort_2[8]))
       ? 6'h3
       : 6'h0)
    | {4'h0,
       hsipriosSort_2[8]
         & (hsipriosSort_3[8] & hsipriosSort_2[7:0] < hsipriosSort_3[7:0]
            | ~(hsipriosSort_3[8])) | hsipriosSort_2[8] & hsipriosSort_3[8]
         & hsipriosSort_2[7:0] == hsipriosSort_3[7:0],
       1'h0};
  wire [8:0]  result_minValue_13 =
    (hsipriosSort_2[8]
     & (hsipriosSort_3[8] & hsipriosSort_2[7:0] < hsipriosSort_3[7:0]
        | ~(hsipriosSort_3[8])) & _hsipriosSort_2_T
       ? _hsipriosSort_2_T_2
       : 9'h0)
    | (hsipriosSort_3[8]
       & (hsipriosSort_2[8] & hsipriosSort_2[7:0] > hsipriosSort_3[7:0]
          | ~(hsipriosSort_2[8])) & _hsipriosSort_3_T
         ? _hsipriosSort_3_T_2
         : 9'h0)
    | (hsipriosSort_2[8] & hsipriosSort_3[8] & hsipriosSort_2[7:0] == hsipriosSort_3[7:0]
       & _hsipriosSort_2_T
         ? _hsipriosSort_2_T_2
         : 9'h0);
  wire        _result_minValue_T_503 = result_minIndex_12 < result_minIndex_13;
  wire [5:0]  result_minIndex_14 =
    (result_minValue_12[8]
     & (result_minValue_13[8] & result_minValue_12[7:0] < result_minValue_13[7:0]
        | ~(result_minValue_13[8]))
       ? result_minIndex_12
       : 6'h0)
    | (result_minValue_13[8]
       & (result_minValue_12[8] & result_minValue_12[7:0] > result_minValue_13[7:0]
          | ~(result_minValue_12[8]))
         ? result_minIndex_13
         : 6'h0)
    | (result_minValue_12[8] & result_minValue_13[8]
       & result_minValue_12[7:0] == result_minValue_13[7:0]
         ? (_result_minValue_T_503 ? result_minIndex_12 : result_minIndex_13)
         : 6'h0);
  wire [8:0]  result_minValue_14 =
    (result_minValue_12[8]
     & (result_minValue_13[8] & result_minValue_12[7:0] < result_minValue_13[7:0]
        | ~(result_minValue_13[8]))
       ? result_minValue_12
       : 9'h0)
    | (result_minValue_13[8]
       & (result_minValue_12[8] & result_minValue_12[7:0] > result_minValue_13[7:0]
          | ~(result_minValue_12[8]))
         ? result_minValue_13
         : 9'h0)
    | (result_minValue_12[8] & result_minValue_13[8]
       & result_minValue_12[7:0] == result_minValue_13[7:0]
         ? (_result_minValue_T_503 ? result_minValue_12 : result_minValue_13)
         : 9'h0);
  wire [5:0]  result_minIndex_15 =
    (hsipriosSort_5[8]
     & (hsipriosSort_4[8] & hsipriosSort_4[7:0] > hsipriosSort_5[7:0]
        | ~(hsipriosSort_4[8]))
       ? 6'h5
       : 6'h0)
    | {3'h0,
       hsipriosSort_4[8]
         & (hsipriosSort_5[8] & hsipriosSort_4[7:0] < hsipriosSort_5[7:0]
            | ~(hsipriosSort_5[8])) | hsipriosSort_4[8] & hsipriosSort_5[8]
         & hsipriosSort_4[7:0] == hsipriosSort_5[7:0],
       2'h0};
  wire [8:0]  result_minValue_15 =
    (hsipriosSort_4[8]
     & (hsipriosSort_5[8] & hsipriosSort_4[7:0] < hsipriosSort_5[7:0]
        | ~(hsipriosSort_5[8])) & _hsipriosSort_4_T
       ? _hsipriosSort_4_T_2
       : 9'h0)
    | (hsipriosSort_5[8]
       & (hsipriosSort_4[8] & hsipriosSort_4[7:0] > hsipriosSort_5[7:0]
          | ~(hsipriosSort_4[8])) & _hsipriosSort_5_T
         ? _hsipriosSort_5_T_2
         : 9'h0)
    | (hsipriosSort_4[8] & hsipriosSort_5[8] & hsipriosSort_4[7:0] == hsipriosSort_5[7:0]
       & _hsipriosSort_4_T
         ? _hsipriosSort_4_T_2
         : 9'h0);
  wire        _result_minValue_T_571 = result_minIndex_15 < 6'h6;
  wire [5:0]  result_minIndex_16 =
    (result_minValue_15[8]
     & (hsipriosSort_6[8] & result_minValue_15[7:0] < hsipriosSort_6[7:0]
        | ~(hsipriosSort_6[8]))
       ? result_minIndex_15
       : 6'h0)
    | (hsipriosSort_6[8]
       & (result_minValue_15[8] & result_minValue_15[7:0] > hsipriosSort_6[7:0]
          | ~(result_minValue_15[8]))
         ? 6'h6
         : 6'h0)
    | (result_minValue_15[8] & hsipriosSort_6[8]
       & result_minValue_15[7:0] == hsipriosSort_6[7:0]
         ? (_result_minValue_T_571 ? result_minIndex_15 : 6'h6)
         : 6'h0);
  wire [8:0]  result_minValue_16 =
    (result_minValue_15[8]
     & (hsipriosSort_6[8] & result_minValue_15[7:0] < hsipriosSort_6[7:0]
        | ~(hsipriosSort_6[8]))
       ? result_minValue_15
       : 9'h0)
    | (hsipriosSort_6[8]
       & (result_minValue_15[8] & result_minValue_15[7:0] > hsipriosSort_6[7:0]
          | ~(result_minValue_15[8])) & _hsipriosSort_6_T
         ? _hsipriosSort_6_T_2
         : 9'h0)
    | (result_minValue_15[8] & hsipriosSort_6[8]
       & result_minValue_15[7:0] == hsipriosSort_6[7:0]
         ? (_result_minValue_T_571 ? result_minValue_15 : hsipriosSort_6)
         : 9'h0);
  wire        _result_minValue_T_605 = result_minIndex_14 < result_minIndex_16;
  wire [5:0]  result_minIndex_17 =
    (result_minValue_14[8]
     & (result_minValue_16[8] & result_minValue_14[7:0] < result_minValue_16[7:0]
        | ~(result_minValue_16[8]))
       ? result_minIndex_14
       : 6'h0)
    | (result_minValue_16[8]
       & (result_minValue_14[8] & result_minValue_14[7:0] > result_minValue_16[7:0]
          | ~(result_minValue_14[8]))
         ? result_minIndex_16
         : 6'h0)
    | (result_minValue_14[8] & result_minValue_16[8]
       & result_minValue_14[7:0] == result_minValue_16[7:0]
         ? (_result_minValue_T_605 ? result_minIndex_14 : result_minIndex_16)
         : 6'h0);
  wire [8:0]  result_minValue_17 =
    (result_minValue_14[8]
     & (result_minValue_16[8] & result_minValue_14[7:0] < result_minValue_16[7:0]
        | ~(result_minValue_16[8]))
       ? result_minValue_14
       : 9'h0)
    | (result_minValue_16[8]
       & (result_minValue_14[8] & result_minValue_14[7:0] > result_minValue_16[7:0]
          | ~(result_minValue_14[8]))
         ? result_minValue_16
         : 9'h0)
    | (result_minValue_14[8] & result_minValue_16[8]
       & result_minValue_14[7:0] == result_minValue_16[7:0]
         ? (_result_minValue_T_605 ? result_minValue_14 : result_minValue_16)
         : 9'h0);
  wire [5:0]  result_minIndex_18 =
    (hsipriosSort_7[8]
     & (hsipriosSort_8[8] & hsipriosSort_7[7:0] < hsipriosSort_8[7:0]
        | ~(hsipriosSort_8[8]))
       ? 6'h7
       : 6'h0)
    | {2'h0,
       hsipriosSort_8[8]
         & (hsipriosSort_7[8] & hsipriosSort_7[7:0] > hsipriosSort_8[7:0]
            | ~(hsipriosSort_7[8])),
       3'h0}
    | (hsipriosSort_7[8] & hsipriosSort_8[8] & hsipriosSort_7[7:0] == hsipriosSort_8[7:0]
         ? 6'h7
         : 6'h0);
  wire [8:0]  result_minValue_18 =
    (hsipriosSort_7[8]
     & (hsipriosSort_8[8] & hsipriosSort_7[7:0] < hsipriosSort_8[7:0]
        | ~(hsipriosSort_8[8])) & _hsipriosSort_7_T
       ? _hsipriosSort_7_T_2
       : 9'h0)
    | (hsipriosSort_8[8]
       & (hsipriosSort_7[8] & hsipriosSort_7[7:0] > hsipriosSort_8[7:0]
          | ~(hsipriosSort_7[8])) & _hsipriosSort_8_T
         ? _hsipriosSort_8_T_2
         : 9'h0)
    | (hsipriosSort_7[8] & hsipriosSort_8[8] & hsipriosSort_7[7:0] == hsipriosSort_8[7:0]
       & _hsipriosSort_7_T
         ? _hsipriosSort_7_T_2
         : 9'h0);
  wire        _result_minValue_T_673 = result_minIndex_18 < 6'h9;
  wire [5:0]  result_minIndex_19 =
    (result_minValue_18[8]
     & (hsipriosSort_9[8] & result_minValue_18[7:0] < hsipriosSort_9[7:0]
        | ~(hsipriosSort_9[8]))
       ? result_minIndex_18
       : 6'h0)
    | (hsipriosSort_9[8]
       & (result_minValue_18[8] & result_minValue_18[7:0] > hsipriosSort_9[7:0]
          | ~(result_minValue_18[8]))
         ? 6'h9
         : 6'h0)
    | (result_minValue_18[8] & hsipriosSort_9[8]
       & result_minValue_18[7:0] == hsipriosSort_9[7:0]
         ? (_result_minValue_T_673 ? result_minIndex_18 : 6'h9)
         : 6'h0);
  wire [8:0]  result_minValue_19 =
    (result_minValue_18[8]
     & (hsipriosSort_9[8] & result_minValue_18[7:0] < hsipriosSort_9[7:0]
        | ~(hsipriosSort_9[8]))
       ? result_minValue_18
       : 9'h0)
    | (hsipriosSort_9[8]
       & (result_minValue_18[8] & result_minValue_18[7:0] > hsipriosSort_9[7:0]
          | ~(result_minValue_18[8])) & _hsipriosSort_9_T
         ? _hsipriosSort_9_T_2
         : 9'h0)
    | (result_minValue_18[8] & hsipriosSort_9[8]
       & result_minValue_18[7:0] == hsipriosSort_9[7:0]
         ? (_result_minValue_T_673 ? result_minValue_18 : hsipriosSort_9)
         : 9'h0);
  wire [5:0]  result_minIndex_20 =
    (hsipriosSort_10[8]
     & (hsipriosSort_11[8] & hsipriosSort_10[7:0] < hsipriosSort_11[7:0]
        | ~(hsipriosSort_11[8]))
       ? 6'hA
       : 6'h0)
    | (hsipriosSort_11[8]
       & (hsipriosSort_10[8] & hsipriosSort_10[7:0] > hsipriosSort_11[7:0]
          | ~(hsipriosSort_10[8]))
         ? 6'hB
         : 6'h0)
    | (hsipriosSort_10[8] & hsipriosSort_11[8]
       & hsipriosSort_10[7:0] == hsipriosSort_11[7:0]
         ? 6'hA
         : 6'h0);
  wire [8:0]  result_minValue_20 =
    (hsipriosSort_10[8]
     & (hsipriosSort_11[8] & hsipriosSort_10[7:0] < hsipriosSort_11[7:0]
        | ~(hsipriosSort_11[8])) & _hsipriosSort_10_T
       ? _hsipriosSort_10_T_2
       : 9'h0)
    | (hsipriosSort_11[8]
       & (hsipriosSort_10[8] & hsipriosSort_10[7:0] > hsipriosSort_11[7:0]
          | ~(hsipriosSort_10[8])) & _hsipriosSort_11_T
         ? _hsipriosSort_11_T_2
         : 9'h0)
    | (hsipriosSort_10[8] & hsipriosSort_11[8]
       & hsipriosSort_10[7:0] == hsipriosSort_11[7:0] & _hsipriosSort_10_T
         ? _hsipriosSort_10_T_2
         : 9'h0);
  wire        _result_minValue_T_741 = result_minIndex_20 < 6'hC;
  wire [5:0]  result_minIndex_21 =
    (result_minValue_20[8]
     & (hsipriosSort_12[8] & result_minValue_20[7:0] < hsipriosSort_12[7:0]
        | ~(hsipriosSort_12[8]))
       ? result_minIndex_20
       : 6'h0)
    | (hsipriosSort_12[8]
       & (result_minValue_20[8] & result_minValue_20[7:0] > hsipriosSort_12[7:0]
          | ~(result_minValue_20[8]))
         ? 6'hC
         : 6'h0)
    | (result_minValue_20[8] & hsipriosSort_12[8]
       & result_minValue_20[7:0] == hsipriosSort_12[7:0]
         ? (_result_minValue_T_741 ? result_minIndex_20 : 6'hC)
         : 6'h0);
  wire [8:0]  result_minValue_21 =
    (result_minValue_20[8]
     & (hsipriosSort_12[8] & result_minValue_20[7:0] < hsipriosSort_12[7:0]
        | ~(hsipriosSort_12[8]))
       ? result_minValue_20
       : 9'h0)
    | (hsipriosSort_12[8]
       & (result_minValue_20[8] & result_minValue_20[7:0] > hsipriosSort_12[7:0]
          | ~(result_minValue_20[8])) & _hsipriosSort_12_T
         ? _hsipriosSort_12_T_2
         : 9'h0)
    | (result_minValue_20[8] & hsipriosSort_12[8]
       & result_minValue_20[7:0] == hsipriosSort_12[7:0]
         ? (_result_minValue_T_741 ? result_minValue_20 : hsipriosSort_12)
         : 9'h0);
  wire        _result_minValue_T_775 = result_minIndex_19 < result_minIndex_21;
  wire [5:0]  result_minIndex_22 =
    (result_minValue_19[8]
     & (result_minValue_21[8] & result_minValue_19[7:0] < result_minValue_21[7:0]
        | ~(result_minValue_21[8]))
       ? result_minIndex_19
       : 6'h0)
    | (result_minValue_21[8]
       & (result_minValue_19[8] & result_minValue_19[7:0] > result_minValue_21[7:0]
          | ~(result_minValue_19[8]))
         ? result_minIndex_21
         : 6'h0)
    | (result_minValue_19[8] & result_minValue_21[8]
       & result_minValue_19[7:0] == result_minValue_21[7:0]
         ? (_result_minValue_T_775 ? result_minIndex_19 : result_minIndex_21)
         : 6'h0);
  wire [8:0]  result_minValue_22 =
    (result_minValue_19[8]
     & (result_minValue_21[8] & result_minValue_19[7:0] < result_minValue_21[7:0]
        | ~(result_minValue_21[8]))
       ? result_minValue_19
       : 9'h0)
    | (result_minValue_21[8]
       & (result_minValue_19[8] & result_minValue_19[7:0] > result_minValue_21[7:0]
          | ~(result_minValue_19[8]))
         ? result_minValue_21
         : 9'h0)
    | (result_minValue_19[8] & result_minValue_21[8]
       & result_minValue_19[7:0] == result_minValue_21[7:0]
         ? (_result_minValue_T_775 ? result_minValue_19 : result_minValue_21)
         : 9'h0);
  wire        _result_minValue_T_809 = result_minIndex_17 < result_minIndex_22;
  wire [5:0]  result_minIndex_23 =
    (result_minValue_17[8]
     & (result_minValue_22[8] & result_minValue_17[7:0] < result_minValue_22[7:0]
        | ~(result_minValue_22[8]))
       ? result_minIndex_17
       : 6'h0)
    | (result_minValue_22[8]
       & (result_minValue_17[8] & result_minValue_17[7:0] > result_minValue_22[7:0]
          | ~(result_minValue_17[8]))
         ? result_minIndex_22
         : 6'h0)
    | (result_minValue_17[8] & result_minValue_22[8]
       & result_minValue_17[7:0] == result_minValue_22[7:0]
         ? (_result_minValue_T_809 ? result_minIndex_17 : result_minIndex_22)
         : 6'h0);
  wire [7:0]  result_minValue_23 =
    (result_minValue_17[8]
     & (result_minValue_22[8] & result_minValue_17[7:0] < result_minValue_22[7:0]
        | ~(result_minValue_22[8]))
       ? result_minValue_17[7:0]
       : 8'h0)
    | (result_minValue_22[8]
       & (result_minValue_17[8] & result_minValue_17[7:0] > result_minValue_22[7:0]
          | ~(result_minValue_17[8]))
         ? result_minValue_22[7:0]
         : 8'h0)
    | (result_minValue_17[8] & result_minValue_22[8]
       & result_minValue_17[7:0] == result_minValue_22[7:0]
         ? (_result_minValue_T_809 ? result_minValue_17[7:0] : result_minValue_22[7:0])
         : 8'h0);
  wire        _mIidNum_select_T_1 = result_1_0 == 6'h0;
  wire [3:0]  _GEN = _mIidNum_select_T_1 | result_1_0 == 6'h1 ? 4'hB : 4'h0;
  wire [3:0]  _GEN_0 =
    {_GEN[3], {_GEN[2], _GEN[1:0] | {2{result_1_0 == 6'h2}}} | {3{result_1_0 == 6'h3}}}
    | (result_1_0 == 6'h4 ? 4'h9 : 4'h0);
  wire [3:0]  _GEN_1 =
    {_GEN_0[3],
     {_GEN_0[2:1], _GEN_0[0] | result_1_0 == 6'h5} | (result_1_0 == 6'h6 ? 3'h5 : 3'h0)}
    | (result_1_0 == 6'h7 ? 4'hC : 4'h0) | (result_1_0 == 6'h8 ? 4'hA : 4'h0);
  wire        _hsIidNum_select_T_1 = result_minIndex_23 == 6'h0;
  wire [3:0]  _GEN_2 = _hsIidNum_select_T_1 | result_minIndex_23 == 6'h1 ? 4'hB : 4'h0;
  wire [3:0]  _GEN_3 =
    {_GEN_2[3],
     {_GEN_2[2], _GEN_2[1:0] | {2{result_minIndex_23 == 6'h2}}}
       | {3{result_minIndex_23 == 6'h3}}} | (result_minIndex_23 == 6'h4 ? 4'h9 : 4'h0);
  wire [3:0]  _GEN_4 =
    {_GEN_3[3],
     {_GEN_3[2:1], _GEN_3[0] | result_minIndex_23 == 6'h5}
       | (result_minIndex_23 == 6'h6 ? 3'h5 : 3'h0)}
    | (result_minIndex_23 == 6'h7 ? 4'hC : 4'h0)
    | (result_minIndex_23 == 6'h8 ? 4'hA : 4'h0);
  wire        Candidate1 =
    io_in_hideleg[53] & io_in_hip[53] & io_in_hie[53] & (|io_in_hstatus_VGEIN)
    & (|{io_in_vstopei_IID, io_in_vstopei_IPRIO});
  wire        Candidate2 =
    io_in_hideleg[53] & io_in_hip[53] & io_in_hie[53] & io_in_hstatus_VGEIN == 6'h0
    & io_in_hvictl_IID == 12'h9 & (|io_in_hvictl_IPRIO);
  wire        Candidate3 =
    io_in_hideleg[53] & io_in_hip[53] & io_in_hie[53] & ~Candidate1 & ~Candidate2;
  wire        Candidate5 = io_in_hvictl_VTI & io_in_hvictl_IID != 12'h9;
  wire [5:0]  VSIidNumTmp_result_minIndex =
    {5'h0,
     hvipriosSort_1[8]
       & (hvipriosSort_0[8] & hvipriosSort_0[7:0] > hvipriosSort_1[7:0]
          | ~(hvipriosSort_0[8]))};
  wire [8:0]  VSIidNumTmp_result_minValue =
    (hvipriosSort_0[8]
     & (hvipriosSort_1[8] & hvipriosSort_0[7:0] < hvipriosSort_1[7:0]
        | ~(hvipriosSort_1[8])) & _hvipriosSort_0_T
       ? _hvipriosSort_0_T_2
       : 9'h0)
    | (hvipriosSort_1[8]
       & (hvipriosSort_0[8] & hvipriosSort_0[7:0] > hvipriosSort_1[7:0]
          | ~(hvipriosSort_0[8])) & _hvipriosSort_1_T
         ? _hvipriosSort_1_T_2
         : 9'h0)
    | (hvipriosSort_0[8] & hvipriosSort_1[8] & hvipriosSort_0[7:0] == hvipriosSort_1[7:0]
       & _hvipriosSort_0_T
         ? _hvipriosSort_0_T_2
         : 9'h0);
  wire [5:0]  VSIidNumTmp_result_1_0 =
    (VSIidNumTmp_result_minValue[8]
     & (hvipriosSort_2[8] & VSIidNumTmp_result_minValue[7:0] < hvipriosSort_2[7:0]
        | ~(hvipriosSort_2[8]))
       ? VSIidNumTmp_result_minIndex
       : 6'h0)
    | {4'h0,
       hvipriosSort_2[8]
         & (VSIidNumTmp_result_minValue[8]
            & VSIidNumTmp_result_minValue[7:0] > hvipriosSort_2[7:0]
            | ~(VSIidNumTmp_result_minValue[8])),
       1'h0}
    | (VSIidNumTmp_result_minValue[8] & hvipriosSort_2[8]
       & VSIidNumTmp_result_minValue[7:0] == hvipriosSort_2[7:0]
         ? (VSIidNumTmp_result_minIndex < 6'h2 ? VSIidNumTmp_result_minIndex : 6'h2)
         : 6'h0);
  wire [8:0]  VSPrioNum_result_minValue =
    (hvipriosSort_0[8]
     & (hvipriosSort_1[8] & hvipriosSort_0[7:0] < hvipriosSort_1[7:0]
        | ~(hvipriosSort_1[8])) & _hvipriosSort_0_T
       ? _hvipriosSort_0_T_2
       : 9'h0)
    | (hvipriosSort_1[8]
       & (hvipriosSort_0[8] & hvipriosSort_0[7:0] > hvipriosSort_1[7:0]
          | ~(hvipriosSort_0[8])) & _hvipriosSort_1_T
         ? _hvipriosSort_1_T_2
         : 9'h0)
    | (hvipriosSort_0[8] & hvipriosSort_1[8] & hvipriosSort_0[7:0] == hvipriosSort_1[7:0]
       & _hvipriosSort_0_T
         ? _hvipriosSort_0_T_2
         : 9'h0);
  wire [10:0] _iprioCandidate123_T_2 = Candidate1 ? io_in_vstopei_IPRIO : 11'h0;
  wire [10:0] _iprioCandidate123_T_6 =
    {_iprioCandidate123_T_2[10:9],
     _iprioCandidate123_T_2[8] | Candidate3,
     _iprioCandidate123_T_2[7:0] | (Candidate2 ? io_in_hvictl_IPRIO : 8'h0)};
  wire [11:0] _iidCandidate45_T_3 =
    {6'h0,
     io_in_hvictl_VTI
       ? 6'h0
       : {3'h0,
          {2'h0, VSIidNumTmp_result_1_0[1:0] == 2'h0}
            | (VSIidNumTmp_result_1_0[1:0] == 2'h1 ? 3'h5 : 3'h0)}
         | ((|(VSIidNumTmp_result_1_0[1:0])) & VSIidNumTmp_result_1_0[1:0] != 2'h1
              ? 6'(VSIidNumTmp_result_1_0 + 6'hB)
              : 6'h0)} | (Candidate5 ? io_in_hvictl_IID : 12'h0);
  wire [10:0] iprioCandidate45 =
    {3'h0,
     (io_in_hvictl_VTI
        ? 8'h0
        : (VSPrioNum_result_minValue[8]
           & (hvipriosSort_2[8] & VSPrioNum_result_minValue[7:0] < hvipriosSort_2[7:0]
              | ~(hvipriosSort_2[8]))
             ? VSPrioNum_result_minValue[7:0]
             : 8'h0)
          | (hvipriosSort_2[8]
             & (VSPrioNum_result_minValue[8]
                & VSPrioNum_result_minValue[7:0] > hvipriosSort_2[7:0]
                | ~(VSPrioNum_result_minValue[8])) & _hvipriosSort_2_T
               ? io_in_hviprio1_PrioCOI
               : 8'h0)
          | (VSPrioNum_result_minValue[8] & hvipriosSort_2[8]
             & VSPrioNum_result_minValue[7:0] == hvipriosSort_2[7:0]
               ? ({5'h0,
                   hvipriosSort_1[8]
                     & (hvipriosSort_0[8] & hvipriosSort_0[7:0] > hvipriosSort_1[7:0]
                        | ~(hvipriosSort_0[8]))} < 6'h2
                    ? VSPrioNum_result_minValue[7:0]
                    : hvipriosSort_2[7:0])
               : 8'h0)) | (Candidate5 ? io_in_hvictl_IPRIO : 8'h0)};
  wire        Candidate123 = Candidate1 | Candidate2 | Candidate3;
  wire        Candidate45 = ~io_in_hvictl_VTI | Candidate5;
  wire        _Candidate123LowCandidate45_T = Candidate123 & ~io_in_hvictl_VTI;
  wire        _Candidate123HighCandidate45_T_33 =
    _iprioCandidate123_T_6 < iprioCandidate45;
  wire        _Candidate123LowCandidate45_T_34 =
    _iprioCandidate123_T_6 == iprioCandidate45;
  wire [3:0]  Candidate123LowCandidate45_select_1 =
    _iidCandidate45_T_3 == 12'h23
      ? 4'hC
      : _iidCandidate45_T_3 == 12'hD
          ? 4'hB
          : _iidCandidate45_T_3 == 12'h6
              ? 4'hA
              : _iidCandidate45_T_3 == 12'h2
                  ? 4'h9
                  : _iidCandidate45_T_3 == 12'hA
                      ? 4'h8
                      : _iidCandidate45_T_3 == 12'hC
                          ? 4'h7
                          : _iidCandidate45_T_3 == 12'h5
                              ? 4'h6
                              : _iidCandidate45_T_3 == 12'h1
                                  ? 4'h5
                                  : _iidCandidate45_T_3 == 12'h9
                                      ? 4'h4
                                      : _iidCandidate45_T_3 == 12'h7
                                          ? 4'h3
                                          : _iidCandidate45_T_3 == 12'h3
                                              ? 4'h2
                                              : {3'h0, _iidCandidate45_T_3 == 12'hB};
  wire        _Candidate123LowCandidate45_T_32 = Candidate123 & Candidate5;
  wire        Candidate123HighCandidate45 =
    _Candidate123LowCandidate45_T
    & (_Candidate123HighCandidate45_T_33 | _Candidate123LowCandidate45_T_34
       & (|(Candidate123LowCandidate45_select_1[3:2]))) | _Candidate123LowCandidate45_T_32
    & (_Candidate123HighCandidate45_T_33 | _Candidate123LowCandidate45_T_34
       & io_in_hvictl_DPR) | Candidate123 & ~Candidate45;
  wire        _Candidate123LowCandidate45_T_33 =
    _iprioCandidate123_T_6 > iprioCandidate45;
  wire        Candidate123LowCandidate45 =
    _Candidate123LowCandidate45_T
    & (_Candidate123LowCandidate45_T_33 | _Candidate123LowCandidate45_T_34
       & Candidate123LowCandidate45_select_1 < 4'h4) | _Candidate123LowCandidate45_T_32
    & (_Candidate123LowCandidate45_T_33 | _Candidate123LowCandidate45_T_34
       & ~io_in_hvictl_DPR) | ~Candidate123 & Candidate45;
  wire [10:0] _iprioCandidate_T_2 =
    (Candidate123HighCandidate45 ? _iprioCandidate123_T_6 : 11'h0)
    | (Candidate123LowCandidate45 ? iprioCandidate45 : 11'h0);
  wire        _GEN_5 = Candidate123LowCandidate45 & Candidate5;
  wire        mIRVec_v_PrvmIsM = &io_in_privState_PRVM;
  wire        mIRVec_isModeM = mIRVec_v_PrvmIsM;
  wire        mIRVec_isModeM_1 = mIRVec_v_PrvmIsM_1;
  wire        mIRVec_isModeHS = PrvmIsS_1;
  wire [63:0] mIRVec =
    mIRVec_isModeM & io_in_mstatusMIE | io_in_privState_V
    & (mIRVec_isModeM_1 | mIRVec_isModeHS) | ~io_in_privState_V
    & io_in_privState_PRVM != 2'h3
      ? mtopigather & ~io_in_mideleg
      : 64'h0;
  wire        hsIRVec_isModeM = hsIRVec_v_PrvmIsM;
  wire        hsIRVec_isModeHS = PrvmIsS_2;
  wire [63:0] hsIRVec =
    stopiIsNotZero_isModeHS & io_in_sstatusSIE | io_in_privState_V
    & (hsIRVec_isModeM | hsIRVec_isModeHS) | ~io_in_privState_V
    & io_in_privState_PRVM == 2'h0
      ? hstopigather & ~io_in_hideleg
      : 64'h0;
  wire        vsIRVec_isModeVS = io_in_privState_V & PrvmIsS;
  wire        vsIRVec_isModeM = vsIRVec_v_PrvmIsM;
  wire [63:0] vsIRVec =
    vsIRVec_isModeVS & io_in_vsstatusSIE | io_in_privState_V
    & (vsIRVec_isModeM | vsIRVec_isModeHS) | io_in_privState_V
    & io_in_privState_PRVM == 2'h0
      ? io_in_vsip & io_in_vsie
      : 64'h0;
  wire [63:0] vsMapHostIRVec =
    {vsIRVec[63:11],
     vsIRVec[9],
     1'h0,
     vsIRVec[8:7],
     vsIRVec[5],
     1'h0,
     vsIRVec[4:3],
     vsIRVec[1],
     1'h0,
     vsIRVec[0]};
  reg  [63:0] intrVecReg;
  wire        disableInterrupt = io_in_debugMode | io_in_dcsr_STEP & ~io_in_dcsr_STEPIE;
  wire [63:0] _intrVec_T_1 = mIRVec | hsIRVec | vsMapHostIRVec;
  wire [17:0] _GEN_6 = _intrVec_T_1[17:0] | {io_in_debugIntr & ~io_in_debugMode, 17'h0};
  always @(posedge clock or posedge reset) begin
    if (reset)
      intrVecReg <= 64'h0;
    else
      intrVecReg <=
        {_intrVec_T_1[63] & ~disableInterrupt,
         _intrVec_T_1[62] & ~disableInterrupt,
         _intrVec_T_1[61] & ~disableInterrupt,
         _intrVec_T_1[60] & ~disableInterrupt,
         _intrVec_T_1[59] & ~disableInterrupt,
         _intrVec_T_1[58] & ~disableInterrupt,
         _intrVec_T_1[57] & ~disableInterrupt,
         _intrVec_T_1[56] & ~disableInterrupt,
         _intrVec_T_1[55] & ~disableInterrupt,
         _intrVec_T_1[54] & ~disableInterrupt,
         _intrVec_T_1[53] & ~disableInterrupt,
         _intrVec_T_1[52] & ~disableInterrupt,
         _intrVec_T_1[51] & ~disableInterrupt,
         _intrVec_T_1[50] & ~disableInterrupt,
         _intrVec_T_1[49] & ~disableInterrupt,
         _intrVec_T_1[48] & ~disableInterrupt,
         _intrVec_T_1[47] & ~disableInterrupt,
         _intrVec_T_1[46] & ~disableInterrupt,
         _intrVec_T_1[45] & ~disableInterrupt,
         _intrVec_T_1[44] & ~disableInterrupt,
         _intrVec_T_1[43] & ~disableInterrupt,
         _intrVec_T_1[42] & ~disableInterrupt,
         _intrVec_T_1[41] & ~disableInterrupt,
         _intrVec_T_1[40] & ~disableInterrupt,
         _intrVec_T_1[39] & ~disableInterrupt,
         _intrVec_T_1[38] & ~disableInterrupt,
         _intrVec_T_1[37] & ~disableInterrupt,
         _intrVec_T_1[36] & ~disableInterrupt,
         _intrVec_T_1[35] & ~disableInterrupt,
         _intrVec_T_1[34] & ~disableInterrupt,
         _intrVec_T_1[33] & ~disableInterrupt,
         _intrVec_T_1[32] & ~disableInterrupt,
         _intrVec_T_1[31] & ~disableInterrupt,
         _intrVec_T_1[30] & ~disableInterrupt,
         _intrVec_T_1[29] & ~disableInterrupt,
         _intrVec_T_1[28] & ~disableInterrupt,
         _intrVec_T_1[27] & ~disableInterrupt,
         _intrVec_T_1[26] & ~disableInterrupt,
         _intrVec_T_1[25] & ~disableInterrupt,
         _intrVec_T_1[24] & ~disableInterrupt,
         _intrVec_T_1[23] & ~disableInterrupt,
         _intrVec_T_1[22] & ~disableInterrupt,
         _intrVec_T_1[21] & ~disableInterrupt,
         _intrVec_T_1[20] & ~disableInterrupt,
         _intrVec_T_1[19] & ~disableInterrupt,
         _intrVec_T_1[18] & ~disableInterrupt,
         _GEN_6[17] & ~disableInterrupt,
         _GEN_6[16] & ~disableInterrupt,
         _GEN_6[15] & ~disableInterrupt,
         _GEN_6[14] & ~disableInterrupt,
         _GEN_6[13] & ~disableInterrupt,
         _GEN_6[12] & ~disableInterrupt,
         _GEN_6[11] & ~disableInterrupt,
         _GEN_6[10] & ~disableInterrupt,
         _GEN_6[9] & ~disableInterrupt,
         _GEN_6[8] & ~disableInterrupt,
         _GEN_6[7] & ~disableInterrupt,
         _GEN_6[6] & ~disableInterrupt,
         _GEN_6[5] & ~disableInterrupt,
         _GEN_6[4] & ~disableInterrupt,
         _GEN_6[3] & ~disableInterrupt,
         _GEN_6[2] & ~disableInterrupt,
         _GEN_6[1] & ~disableInterrupt,
         _GEN_6[0] & ~disableInterrupt};
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        intrVecReg = {_RANDOM[1'h0], _RANDOM[1'h1]};
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        intrVecReg = 64'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DelayN_230 delayedIntrVec_delay (
    .clock  (clock),
    .io_in  (intrVecReg),
    .io_out (_delayedIntrVec_delay_io_out)
  );
  assign io_out_interruptVec_valid = |_delayedIntrVec_delay_io_out;
  assign io_out_interruptVec_bits = _delayedIntrVec_delay_io_out;
  assign io_out_mtopi_IID =
    {6'h0,
     (|_mtopiIsNotZero_T_2)
       ? {_mIidNum_select_T_1,
          1'h0,
          {_GEN_1[3],
           {_GEN_1[2], _GEN_1[1:0] | {result_1_0 == 6'h9, 1'h0}}
             | (result_1_0 == 6'hA ? 3'h6 : 3'h0)} | (result_1_0 == 6'hB ? 4'hD : 4'h0)}
         | (result_1_0 == 6'hC ? 6'h23 : 6'h0)
       : 6'h0};
  assign io_out_mtopi_IPRIO =
    (|_mtopiIsNotZero_T_2)
      ? (io_in_miprios == 512'h0
           ? 8'h1
           : ((|result_2_0) ? result_2_0 : 8'h0)
             | {8{result_2_0 == 8'h0 & (|(result_1_0[5:1]))}})
      : 8'h0;
  assign io_out_stopi_IID =
    {6'h0,
     stopiIsNotZero
       ? {_hsIidNum_select_T_1,
          1'h0,
          {_GEN_4[3],
           {_GEN_4[2], _GEN_4[1:0] | {result_minIndex_23 == 6'h9, 1'h0}}
             | (result_minIndex_23 == 6'hA ? 3'h6 : 3'h0)}
            | (result_minIndex_23 == 6'hB ? 4'hD : 4'h0)}
         | (result_minIndex_23 == 6'hC ? 6'h23 : 6'h0)
       : 6'h0};
  assign io_out_stopi_IPRIO =
    stopiIsNotZero
      ? (io_in_hsiprios == 512'h0
           ? 8'h1
           : ((|result_minValue_23) ? result_minValue_23 : 8'h0)
             | {8{result_minValue_23 == 8'h0 & result_minIndex_23 > 6'h4}})
      : 8'h0;
  assign io_out_vstopi_IID =
    ~Candidate1 & ~Candidate2 & ~Candidate3 & io_in_hvictl_VTI & ~Candidate5
      ? 12'h0
      : (Candidate123HighCandidate45 ? 12'h9 : 12'h0)
        | (Candidate123LowCandidate45 ? _iidCandidate45_T_3 : 12'h0);
  assign io_out_vstopi_IPRIO =
    {{7{|(_iprioCandidate_T_2[10:8])}},
     (|(_iprioCandidate_T_2[10:8])) | _GEN_5 & ~io_in_hvictl_IPRIOM}
    | (Candidate123HighCandidate45 & _iprioCandidate_T_2 < 11'h100
       | Candidate123LowCandidate45 & ~io_in_hvictl_VTI | _GEN_5 & io_in_hvictl_IPRIOM
         ? _iprioCandidate_T_2[7:0]
         : 8'h0);
endmodule

