// Generated by CIRCT firtool-1.74.0
module IntToFP_postnorm(
  input  [62:0] io_in_norm_int,
  input  [5:0]  io_in_lzc,
  input         io_in_is_zero,
  input         io_in_sign,
  input  [2:0]  io_rm,
  output [31:0] io_result,
  output [4:0]  io_fflags
);

  wire [22:0] _rounder_io_out;
  wire        _rounder_io_inexact;
  wire        _rounder_io_cout;
  RoundingUnit rounder (
    .io_in       (io_in_norm_int[62:40]),
    .io_roundIn  (io_in_norm_int[39]),
    .io_stickyIn (|(io_in_norm_int[38:0])),
    .io_signIn   (io_in_sign),
    .io_rm       (io_rm),
    .io_out      (_rounder_io_out),
    .io_inexact  (_rounder_io_inexact),
    .io_cout     (_rounder_io_cout)
  );
  assign io_result =
    {io_in_sign,
     io_in_is_zero ? 8'h0 : 8'(8'(8'hBE - {2'h0, io_in_lzc}) + {7'h0, _rounder_io_cout}),
     _rounder_io_out};
  assign io_fflags = {4'h0, _rounder_io_inexact};
endmodule

