// Generated by CIRCT firtool-1.74.0
module IntToFP_1(
  input  [63:0] io_int,
  input         io_sign,
  input         io_long,
  input  [2:0]  io_rm,
  output [63:0] io_result,
  output [4:0]  io_fflags
);

  wire [62:0] _pre_norm_io_out_norm_int;
  wire [5:0]  _pre_norm_io_out_lzc;
  wire        _pre_norm_io_out_is_zero;
  wire        _pre_norm_io_out_sign;
  IntToFP_prenorm pre_norm (
    .io_in_int       (io_int),
    .io_in_sign      (io_sign),
    .io_in_long      (io_long),
    .io_out_norm_int (_pre_norm_io_out_norm_int),
    .io_out_lzc      (_pre_norm_io_out_lzc),
    .io_out_is_zero  (_pre_norm_io_out_is_zero),
    .io_out_sign     (_pre_norm_io_out_sign)
  );
  IntToFP_postnorm_1 post_norm (
    .io_in_norm_int (_pre_norm_io_out_norm_int),
    .io_in_lzc      (_pre_norm_io_out_lzc),
    .io_in_is_zero  (_pre_norm_io_out_is_zero),
    .io_in_sign     (_pre_norm_io_out_sign),
    .io_rm          (io_rm),
    .io_result      (io_result),
    .io_fflags      (io_fflags)
  );
endmodule

