// Generated by CIRCT firtool-1.74.0
module IntToFP_postnorm_1(
  input  [62:0] io_in_norm_int,
  input  [5:0]  io_in_lzc,
  input         io_in_is_zero,
  input         io_in_sign,
  input  [2:0]  io_rm,
  output [63:0] io_result,
  output [4:0]  io_fflags
);

  wire [51:0] _rounder_io_out;
  wire        _rounder_io_inexact;
  wire        _rounder_io_cout;
  RoundingUnit_1 rounder (
    .io_in       (io_in_norm_int[62:11]),
    .io_roundIn  (io_in_norm_int[10]),
    .io_stickyIn (|(io_in_norm_int[9:0])),
    .io_signIn   (io_in_sign),
    .io_rm       (io_rm),
    .io_out      (_rounder_io_out),
    .io_inexact  (_rounder_io_inexact),
    .io_cout     (_rounder_io_cout)
  );
  assign io_result =
    {io_in_sign,
     io_in_is_zero
       ? 11'h0
       : 11'(11'(11'h43E - {5'h0, io_in_lzc}) + {10'h0, _rounder_io_cout}),
     _rounder_io_out};
  assign io_fflags = {4'h0, _rounder_io_inexact};
endmodule

