// Generated by CIRCT firtool-1.74.0
module lzc(
  input  [52:0] in_i,
  output [5:0]  cnt_o,
  output        empty_o
);

  wire        _empty_o_output;
  wire [18:0] _GEN =
    {in_i[5:4],
     in_i[7:6],
     in_i[9:8],
     in_i[11:10],
     in_i[13:12],
     in_i[15:14],
     in_i[17:16],
     in_i[19:18],
     in_i[21:20],
     in_i[23]} & 19'h55555;
  wire [3:0]  _GEN_0 = _GEN[18:15] | {in_i[7:6], in_i[9:8]} & 4'h5;
  wire [3:0]  _GEN_1 = _GEN[10:7] | {in_i[15:14], in_i[17:16]} & 4'h5;
  wire [3:0]  _GEN_2 = {_GEN[2:0], 1'h0} | {in_i[23:22], in_i[25:24]} & 4'h5;
  assign _empty_o_output = in_i == 53'h0;
  assign cnt_o =
    _empty_o_output | in_i[52]
      ? 6'h0
      : in_i[51]
          ? 6'h1
          : in_i[50]
              ? 6'h2
              : in_i[49]
                  ? 6'h3
                  : in_i[48]
                      ? 6'h4
                      : in_i[47]
                          ? 6'h5
                          : in_i[46]
                              ? 6'h6
                              : in_i[45]
                                  ? 6'h7
                                  : in_i[44]
                                      ? 6'h8
                                      : in_i[43]
                                          ? 6'h9
                                          : in_i[42]
                                              ? 6'hA
                                              : in_i[41]
                                                  ? 6'hB
                                                  : in_i[40]
                                                      ? 6'hC
                                                      : in_i[39]
                                                          ? 6'hD
                                                          : in_i[38]
                                                              ? 6'hE
                                                              : in_i[37]
                                                                  ? 6'hF
                                                                  : in_i[36]
                                                                      ? 6'h10
                                                                      : in_i[35]
                                                                          ? 6'h11
                                                                          : in_i[34]
                                                                              ? 6'h12
                                                                              : in_i[33]
                                                                                  ? 6'h13
                                                                                  : in_i[32]
                                                                                      ? 6'h14
                                                                                      : in_i[31]
                                                                                          ? 6'h15
                                                                                          : in_i[30]
                                                                                              ? 6'h16
                                                                                              : in_i[29]
                                                                                                  ? 6'h17
                                                                                                  : in_i[28]
                                                                                                      ? 6'h18
                                                                                                      : in_i[27]
                                                                                                          ? 6'h19
                                                                                                          : in_i[26]
                                                                                                              ? 6'h1A
                                                                                                              : in_i[25]
                                                                                                                  ? 6'h1B
                                                                                                                  : _GEN_2[0]
                                                                                                                      ? 6'h1C
                                                                                                                      : _GEN_2[1]
                                                                                                                          ? 6'h1D
                                                                                                                          : _GEN_2[2]
                                                                                                                              ? 6'h1E
                                                                                                                              : _GEN_2[3]
                                                                                                                                  ? 6'h1F
                                                                                                                                  : in_i[20]
                                                                                                                                      ? 6'h20
                                                                                                                                      : in_i[19]
                                                                                                                                          ? 6'h21
                                                                                                                                          : _GEN[5]
                                                                                                                                            | in_i[18]
                                                                                                                                              ? 6'h22
                                                                                                                                              : in_i[17]
                                                                                                                                                  ? 6'h23
                                                                                                                                                  : _GEN_1[0]
                                                                                                                                                      ? 6'h24
                                                                                                                                                      : _GEN_1[1]
                                                                                                                                                          ? 6'h25
                                                                                                                                                          : _GEN_1[2]
                                                                                                                                                              ? 6'h26
                                                                                                                                                              : _GEN_1[3]
                                                                                                                                                                  ? 6'h27
                                                                                                                                                                  : in_i[12]
                                                                                                                                                                      ? 6'h28
                                                                                                                                                                      : in_i[11]
                                                                                                                                                                          ? 6'h29
                                                                                                                                                                          : _GEN[13]
                                                                                                                                                                            | in_i[10]
                                                                                                                                                                              ? 6'h2A
                                                                                                                                                                              : in_i[9]
                                                                                                                                                                                  ? 6'h2B
                                                                                                                                                                                  : _GEN_0[0]
                                                                                                                                                                                      ? 6'h2C
                                                                                                                                                                                      : _GEN_0[1]
                                                                                                                                                                                          ? 6'h2D
                                                                                                                                                                                          : _GEN_0[2]
                                                                                                                                                                                              ? 6'h2E
                                                                                                                                                                                              : _GEN_0[3]
                                                                                                                                                                                                  ? 6'h2F
                                                                                                                                                                                                  : in_i[4]
                                                                                                                                                                                                      ? 6'h30
                                                                                                                                                                                                      : in_i[3]
                                                                                                                                                                                                          ? 6'h31
                                                                                                                                                                                                          : in_i[2]
                                                                                                                                                                                                              ? 6'h32
                                                                                                                                                                                                              : in_i[1]
                                                                                                                                                                                                                  ? 6'h33
                                                                                                                                                                                                                  : 6'h34;
  assign empty_o = _empty_o_output;
endmodule

