// Generated by CIRCT firtool-1.74.0
module Mhpmevent17Module(
  output [63:0] rdata,
  output        regOut_OF,
  output        regOut_MINH,
  output        regOut_SINH,
  output        regOut_UINH,
  output        regOut_VSINH,
  output        regOut_VUINH,
  input  [63:0] perfEvents_14
);

  assign rdata = {perfEvents_14[63:58], 58'h0};
  assign regOut_OF = perfEvents_14[63];
  assign regOut_MINH = perfEvents_14[62];
  assign regOut_SINH = perfEvents_14[61];
  assign regOut_UINH = perfEvents_14[60];
  assign regOut_VSINH = perfEvents_14[59];
  assign regOut_VUINH = perfEvents_14[58];
endmodule

