// Generated by CIRCT firtool-1.74.0
module Mhpmevent10Module(
  output [63:0] rdata,
  output        regOut_OF,
  output        regOut_MINH,
  output        regOut_SINH,
  output        regOut_UINH,
  output        regOut_VSINH,
  output        regOut_VUINH,
  input  [63:0] perfEvents_7
);

  assign rdata = {perfEvents_7[63:58], 58'h0};
  assign regOut_OF = perfEvents_7[63];
  assign regOut_MINH = perfEvents_7[62];
  assign regOut_SINH = perfEvents_7[61];
  assign regOut_UINH = perfEvents_7[60];
  assign regOut_VSINH = perfEvents_7[59];
  assign regOut_VUINH = perfEvents_7[58];
endmodule

