// Generated by CIRCT firtool-1.74.0
module Mhpmevent22Module(
  output [63:0] rdata,
  output        regOut_OF,
  output        regOut_MINH,
  output        regOut_SINH,
  output        regOut_UINH,
  output        regOut_VSINH,
  output        regOut_VUINH,
  input  [63:0] perfEvents_19
);

  assign rdata = {perfEvents_19[63:58], 58'h0};
  assign regOut_OF = perfEvents_19[63];
  assign regOut_MINH = perfEvents_19[62];
  assign regOut_SINH = perfEvents_19[61];
  assign regOut_UINH = perfEvents_19[60];
  assign regOut_VSINH = perfEvents_19[59];
  assign regOut_VUINH = perfEvents_19[58];
endmodule

