// Generated by CIRCT firtool-1.74.0
module Mhpmevent9Module(
  output [63:0] rdata,
  output        regOut_OF,
  output        regOut_MINH,
  output        regOut_SINH,
  output        regOut_UINH,
  output        regOut_VSINH,
  output        regOut_VUINH,
  input  [63:0] perfEvents_6
);

  assign rdata = {perfEvents_6[63:58], 58'h0};
  assign regOut_OF = perfEvents_6[63];
  assign regOut_MINH = perfEvents_6[62];
  assign regOut_SINH = perfEvents_6[61];
  assign regOut_UINH = perfEvents_6[60];
  assign regOut_VSINH = perfEvents_6[59];
  assign regOut_VUINH = perfEvents_6[58];
endmodule

