// Generated by CIRCT firtool-1.74.0
module MtopiModule(
  output [63:0] rdata,
  output [11:0] regOut_IID,
  output [7:0]  regOut_IPRIO,
  input  [11:0] topIR_mtopi_IID,
  input  [7:0]  topIR_mtopi_IPRIO
);

  assign rdata = {36'h0, topIR_mtopi_IID, 8'h0, topIR_mtopi_IPRIO};
  assign regOut_IID = topIR_mtopi_IID;
  assign regOut_IPRIO = topIR_mtopi_IPRIO;
endmodule

