// Generated by CIRCT firtool-1.74.0
module RXDAT(
  input          io_out_valid,
  input  [7:0]   io_out_bits_txnID,
  input  [6:0]   io_out_bits_homeNID,
  input  [2:0]   io_out_bits_opcode,
  input  [2:0]   io_out_bits_resp,
  input  [7:0]   io_out_bits_dbID,
  input  [1:0]   io_out_bits_dataID,
  input  [255:0] io_out_bits_data,
  output         io_in_valid,
  output [7:0]   io_in_mshrId,
  output [5:0]   io_in_respInfo_chiOpcode,
  output [6:0]   io_in_respInfo_homeNID,
  output [7:0]   io_in_respInfo_dbID,
  output [2:0]   io_in_respInfo_resp,
  output         io_refillBufWrite_valid,
  output [7:0]   io_refillBufWrite_bits_id,
  output [511:0] io_refillBufWrite_bits_data_data,
  output [1:0]   io_refillBufWrite_bits_beatMask
);

  wire first = io_out_bits_dataID == 2'h0;
  wire last = io_out_bits_dataID == 2'h2;
  assign io_in_valid = (first | last) & io_out_valid;
  assign io_in_mshrId = io_out_bits_txnID;
  assign io_in_respInfo_chiOpcode = {3'h0, io_out_bits_opcode};
  assign io_in_respInfo_homeNID = io_out_bits_homeNID;
  assign io_in_respInfo_dbID = io_out_bits_dbID;
  assign io_in_respInfo_resp = io_out_bits_resp;
  assign io_refillBufWrite_valid = io_out_valid;
  assign io_refillBufWrite_bits_id = io_out_bits_txnID;
  assign io_refillBufWrite_bits_data_data = {2{io_out_bits_data}};
  assign io_refillBufWrite_bits_beatMask = {last, first};
endmodule

