// Generated by CIRCT firtool-1.74.0
module SRAMTemplate_143(
  input          clock,
  input          io_r_req_valid,
  input  [11:0]  io_r_req_bits_setIdx,
  output [511:0] io_r_resp_data_0_data,
  input          io_w_req_valid,
  input  [11:0]  io_w_req_bits_setIdx,
  input  [511:0] io_w_req_bits_data_0_data
);

  wire realRen;
  assign realRen = io_r_req_valid & ~io_w_req_valid;
  array_mcp2_0 array_mcp2_0 (
    .RW0_addr  (io_w_req_valid ? io_w_req_bits_setIdx : io_r_req_bits_setIdx),
    .RW0_en    (realRen | io_w_req_valid),
    .RW0_clk   (clock),
    .RW0_wmode (io_w_req_valid),
    .RW0_wdata (io_w_req_bits_data_0_data),
    .RW0_rdata (io_r_resp_data_0_data)
  );
endmodule

