// Generated by CIRCT firtool-1.74.0
module VCVT_1(
  input         clock,
  input         reset,
  input         io_fire,
  input  [31:0] io_src,
  input  [7:0]  io_opType,
  input  [1:0]  io_sew,
  input  [2:0]  io_rm,
  output [31:0] io_result,
  output [4:0]  io_fflags
);

  CVT32 vcvtImpl (
    .clock     (clock),
    .reset     (reset),
    .io_fire   (io_fire),
    .io_src    (io_src),
    .io_opType (io_opType),
    .io_sew    (io_sew),
    .io_rm     (io_rm),
    .io_result (io_result),
    .io_fflags (io_fflags)
  );
endmodule

