// Generated by CIRCT firtool-1.74.0
module VStopiModule(
  output [63:0] rdata,
  output [11:0] regOut_IID,
  output [7:0]  regOut_IPRIO,
  input  [11:0] topIR_vstopi_IID,
  input  [7:0]  topIR_vstopi_IPRIO
);

  assign rdata = {36'h0, topIR_vstopi_IID, 8'h0, topIR_vstopi_IPRIO};
  assign regOut_IID = topIR_vstopi_IID;
  assign regOut_IPRIO = topIR_vstopi_IPRIO;
endmodule

