// Generated by CIRCT firtool-1.74.0
module XSTile(
  input          clock,
  input          reset,
  output         auto_l2top_beu_int_out_0,
  input          auto_l2top_plic_int_in_1_0,
  input          auto_l2top_plic_int_in_0_0,
  input          auto_l2top_debug_int_in_0,
  input          auto_l2top_clint_int_in_0,
  input          auto_l2top_clint_int_in_1,
  input  [5:0]   io_hartId,
  input          io_msiInfo_valid,
  input  [16:0]  io_msiInfo_bits_info,
  input  [35:0]  io_reset_vector,
  output         io_cpu_halt,
  output         io_chi_txsactive,
  input          io_chi_rxsactive,
  output         io_chi_tx_linkactivereq,
  input          io_chi_tx_linkactiveack,
  output         io_chi_tx_req_flitpend,
  output         io_chi_tx_req_flitv,
  output [124:0] io_chi_tx_req_flit,
  input          io_chi_tx_req_lcrdv,
  output         io_chi_tx_rsp_flitpend,
  output         io_chi_tx_rsp_flitv,
  output [50:0]  io_chi_tx_rsp_flit,
  input          io_chi_tx_rsp_lcrdv,
  output         io_chi_tx_dat_flitpend,
  output         io_chi_tx_dat_flitv,
  output [348:0] io_chi_tx_dat_flit,
  input          io_chi_tx_dat_lcrdv,
  input          io_chi_rx_linkactivereq,
  output         io_chi_rx_linkactiveack,
  input          io_chi_rx_rsp_flitpend,
  input          io_chi_rx_rsp_flitv,
  input  [50:0]  io_chi_rx_rsp_flit,
  output         io_chi_rx_rsp_lcrdv,
  input          io_chi_rx_dat_flitpend,
  input          io_chi_rx_dat_flitv,
  input  [348:0] io_chi_rx_dat_flit,
  output         io_chi_rx_dat_lcrdv,
  input          io_chi_rx_snp_flitpend,
  input          io_chi_rx_snp_flitv,
  input  [87:0]  io_chi_rx_snp_flit,
  output         io_chi_rx_snp_lcrdv,
  input  [6:0]   io_nodeID,
  input          io_clintTime_valid,
  input  [63:0]  io_clintTime_bits
);

  wire         _l2top_auto_buffers_in_a_ready;
  wire         _l2top_auto_buffers_in_d_valid;
  wire [2:0]   _l2top_auto_buffers_in_d_bits_opcode;
  wire         _l2top_auto_buffers_in_d_bits_denied;
  wire [63:0]  _l2top_auto_buffers_in_d_bits_data;
  wire         _l2top_auto_i_mmio_buffer_in_a_ready;
  wire         _l2top_auto_i_mmio_buffer_in_d_valid;
  wire [2:0]   _l2top_auto_i_mmio_buffer_in_d_bits_opcode;
  wire [1:0]   _l2top_auto_i_mmio_buffer_in_d_bits_param;
  wire [1:0]   _l2top_auto_i_mmio_buffer_in_d_bits_size;
  wire         _l2top_auto_i_mmio_buffer_in_d_bits_source;
  wire         _l2top_auto_i_mmio_buffer_in_d_bits_sink;
  wire         _l2top_auto_i_mmio_buffer_in_d_bits_denied;
  wire [63:0]  _l2top_auto_i_mmio_buffer_in_d_bits_data;
  wire         _l2top_auto_i_mmio_buffer_in_d_bits_corrupt;
  wire         _l2top_auto_ptw_to_l2_buffer_in_a_ready;
  wire         _l2top_auto_ptw_to_l2_buffer_in_d_valid;
  wire [2:0]   _l2top_auto_ptw_to_l2_buffer_in_d_bits_opcode;
  wire [1:0]   _l2top_auto_ptw_to_l2_buffer_in_d_bits_param;
  wire [2:0]   _l2top_auto_ptw_to_l2_buffer_in_d_bits_size;
  wire [2:0]   _l2top_auto_ptw_to_l2_buffer_in_d_bits_source;
  wire [9:0]   _l2top_auto_ptw_to_l2_buffer_in_d_bits_sink;
  wire         _l2top_auto_ptw_to_l2_buffer_in_d_bits_denied;
  wire [255:0] _l2top_auto_ptw_to_l2_buffer_in_d_bits_data;
  wire         _l2top_auto_ptw_to_l2_buffer_in_d_bits_corrupt;
  wire         _l2top_auto_xbar_in_1_a_ready;
  wire         _l2top_auto_xbar_in_1_d_valid;
  wire [2:0]   _l2top_auto_xbar_in_1_d_bits_opcode;
  wire [1:0]   _l2top_auto_xbar_in_1_d_bits_param;
  wire [2:0]   _l2top_auto_xbar_in_1_d_bits_size;
  wire [3:0]   _l2top_auto_xbar_in_1_d_bits_source;
  wire [9:0]   _l2top_auto_xbar_in_1_d_bits_sink;
  wire         _l2top_auto_xbar_in_1_d_bits_denied;
  wire [255:0] _l2top_auto_xbar_in_1_d_bits_data;
  wire         _l2top_auto_xbar_in_1_d_bits_corrupt;
  wire         _l2top_auto_xbar_in_0_a_ready;
  wire         _l2top_auto_xbar_in_0_b_valid;
  wire [2:0]   _l2top_auto_xbar_in_0_b_bits_opcode;
  wire [1:0]   _l2top_auto_xbar_in_0_b_bits_param;
  wire [2:0]   _l2top_auto_xbar_in_0_b_bits_size;
  wire [5:0]   _l2top_auto_xbar_in_0_b_bits_source;
  wire [35:0]  _l2top_auto_xbar_in_0_b_bits_address;
  wire [31:0]  _l2top_auto_xbar_in_0_b_bits_mask;
  wire [255:0] _l2top_auto_xbar_in_0_b_bits_data;
  wire         _l2top_auto_xbar_in_0_b_bits_corrupt;
  wire         _l2top_auto_xbar_in_0_c_ready;
  wire         _l2top_auto_xbar_in_0_d_valid;
  wire [2:0]   _l2top_auto_xbar_in_0_d_bits_opcode;
  wire [1:0]   _l2top_auto_xbar_in_0_d_bits_param;
  wire [2:0]   _l2top_auto_xbar_in_0_d_bits_size;
  wire [5:0]   _l2top_auto_xbar_in_0_d_bits_source;
  wire [9:0]   _l2top_auto_xbar_in_0_d_bits_sink;
  wire         _l2top_auto_xbar_in_0_d_bits_denied;
  wire         _l2top_auto_xbar_in_0_d_bits_echo_isKeyword;
  wire [255:0] _l2top_auto_xbar_in_0_d_bits_data;
  wire         _l2top_auto_xbar_in_0_d_bits_corrupt;
  wire         _l2top_auto_xbar_in_0_e_ready;
  wire         _l2top_auto_plic_int_out_1_0;
  wire         _l2top_auto_plic_int_out_0_0;
  wire         _l2top_auto_debug_int_out_0;
  wire         _l2top_auto_clint_int_out_0;
  wire         _l2top_auto_clint_int_out_1;
  wire [35:0]  _l2top_reset_vector_toCore;
  wire [63:0]  _l2top_hartId_toCore;
  wire         _l2top_l2_tlb_req_req_valid;
  wire [40:0]  _l2top_l2_tlb_req_req_bits_vaddr;
  wire [2:0]   _l2top_l2_tlb_req_req_bits_cmd;
  wire         _l2top_l2_tlb_req_req_bits_kill;
  wire         _l2top_l2_tlb_req_req_bits_no_translate;
  wire         _l2top_l2_hint_valid;
  wire [3:0]   _l2top_l2_hint_bits_sourceId;
  wire         _l2top_l2_hint_bits_isKeyword;
  wire         _core_auto_memBlock_frontendBridge_instr_uncache_out_a_valid;
  wire [2:0]   _core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_param;
  wire [30:0]  _core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_address;
  wire         _core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_corrupt;
  wire         _core_auto_memBlock_frontendBridge_instr_uncache_out_d_ready;
  wire         _core_auto_memBlock_frontendBridge_icache_out_a_valid;
  wire [2:0]   _core_auto_memBlock_frontendBridge_icache_out_a_bits_opcode;
  wire [2:0]   _core_auto_memBlock_frontendBridge_icache_out_a_bits_param;
  wire [2:0]   _core_auto_memBlock_frontendBridge_icache_out_a_bits_size;
  wire [3:0]   _core_auto_memBlock_frontendBridge_icache_out_a_bits_source;
  wire [35:0]  _core_auto_memBlock_frontendBridge_icache_out_a_bits_address;
  wire         _core_auto_memBlock_frontendBridge_icache_out_a_bits_user_alias;
  wire [3:0]   _core_auto_memBlock_frontendBridge_icache_out_a_bits_user_reqSource;
  wire         _core_auto_memBlock_frontendBridge_icache_out_a_bits_user_needHint;
  wire [31:0]  _core_auto_memBlock_frontendBridge_icache_out_a_bits_mask;
  wire [255:0] _core_auto_memBlock_frontendBridge_icache_out_a_bits_data;
  wire         _core_auto_memBlock_frontendBridge_icache_out_a_bits_corrupt;
  wire         _core_auto_memBlock_frontendBridge_icache_out_d_ready;
  wire         _core_auto_memBlock_ptw_to_l2_buffer_out_a_valid;
  wire [2:0]   _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_opcode;
  wire [2:0]   _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_param;
  wire [2:0]   _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_size;
  wire [2:0]   _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_source;
  wire [35:0]  _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_address;
  wire [3:0]   _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_user_reqSource;
  wire [31:0]  _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_mask;
  wire [255:0] _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_data;
  wire         _core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_corrupt;
  wire         _core_auto_memBlock_ptw_to_l2_buffer_out_d_ready;
  wire         _core_auto_memBlock_uncache_client_out_a_valid;
  wire [2:0]   _core_auto_memBlock_uncache_client_out_a_bits_opcode;
  wire [1:0]   _core_auto_memBlock_uncache_client_out_a_bits_size;
  wire [1:0]   _core_auto_memBlock_uncache_client_out_a_bits_source;
  wire [30:0]  _core_auto_memBlock_uncache_client_out_a_bits_address;
  wire [7:0]   _core_auto_memBlock_uncache_client_out_a_bits_mask;
  wire [63:0]  _core_auto_memBlock_uncache_client_out_a_bits_data;
  wire         _core_auto_memBlock_uncache_client_out_d_ready;
  wire [63:0]  _core_auto_memBlock_l2_pf_sender_out_addr;
  wire [3:0]   _core_auto_memBlock_l2_pf_sender_out_pf_source;
  wire         _core_auto_memBlock_l2_pf_sender_out_addr_valid;
  wire         _core_auto_memBlock_l2_pf_sender_out_l2_pf_en;
  wire         _core_auto_memBlock_dcache_client_out_a_valid;
  wire [2:0]   _core_auto_memBlock_dcache_client_out_a_bits_opcode;
  wire [2:0]   _core_auto_memBlock_dcache_client_out_a_bits_param;
  wire [2:0]   _core_auto_memBlock_dcache_client_out_a_bits_size;
  wire [5:0]   _core_auto_memBlock_dcache_client_out_a_bits_source;
  wire [35:0]  _core_auto_memBlock_dcache_client_out_a_bits_address;
  wire         _core_auto_memBlock_dcache_client_out_a_bits_user_alias;
  wire [34:0]  _core_auto_memBlock_dcache_client_out_a_bits_user_vaddr;
  wire [3:0]   _core_auto_memBlock_dcache_client_out_a_bits_user_reqSource;
  wire         _core_auto_memBlock_dcache_client_out_a_bits_user_needHint;
  wire         _core_auto_memBlock_dcache_client_out_a_bits_echo_isKeyword;
  wire [31:0]  _core_auto_memBlock_dcache_client_out_a_bits_mask;
  wire [255:0] _core_auto_memBlock_dcache_client_out_a_bits_data;
  wire         _core_auto_memBlock_dcache_client_out_a_bits_corrupt;
  wire         _core_auto_memBlock_dcache_client_out_b_ready;
  wire         _core_auto_memBlock_dcache_client_out_c_valid;
  wire [2:0]   _core_auto_memBlock_dcache_client_out_c_bits_opcode;
  wire [2:0]   _core_auto_memBlock_dcache_client_out_c_bits_param;
  wire [2:0]   _core_auto_memBlock_dcache_client_out_c_bits_size;
  wire [5:0]   _core_auto_memBlock_dcache_client_out_c_bits_source;
  wire [35:0]  _core_auto_memBlock_dcache_client_out_c_bits_address;
  wire         _core_auto_memBlock_dcache_client_out_c_bits_user_alias;
  wire [34:0]  _core_auto_memBlock_dcache_client_out_c_bits_user_vaddr;
  wire [3:0]   _core_auto_memBlock_dcache_client_out_c_bits_user_reqSource;
  wire         _core_auto_memBlock_dcache_client_out_c_bits_user_needHint;
  wire         _core_auto_memBlock_dcache_client_out_c_bits_echo_isKeyword;
  wire [255:0] _core_auto_memBlock_dcache_client_out_c_bits_data;
  wire         _core_auto_memBlock_dcache_client_out_c_bits_corrupt;
  wire         _core_auto_memBlock_dcache_client_out_d_ready;
  wire         _core_auto_memBlock_dcache_client_out_e_valid;
  wire [9:0]   _core_auto_memBlock_dcache_client_out_e_bits_sink;
  wire         _core_io_cpu_halt;
  wire         _core_io_beu_errors_icache_ecc_error_valid;
  wire [35:0]  _core_io_beu_errors_icache_ecc_error_bits;
  wire         _core_io_beu_errors_dcache_ecc_error_valid;
  wire [35:0]  _core_io_beu_errors_dcache_ecc_error_bits;
  wire         _core_io_l2_tlb_req_resp_valid;
  wire [35:0]  _core_io_l2_tlb_req_resp_bits_paddr_0;
  wire         _core_io_l2_tlb_req_resp_bits_miss;
  wire         _core_io_l2_tlb_req_resp_bits_excp_0_pf_ld;
  wire         _core_io_l2_tlb_req_resp_bits_excp_0_pf_st;
  wire         _core_io_l2_tlb_req_resp_bits_excp_0_af_ld;
  wire         _core_io_l2_tlb_req_resp_bits_excp_0_af_st;
  wire         _core_io_l2_pmp_resp_mmio;
  XSCore core (
    .clock                                                         (clock),
    .reset                                                         (reset),
    .auto_memBlock_frontendBridge_instr_uncache_out_a_ready
      (_l2top_auto_i_mmio_buffer_in_a_ready),
    .auto_memBlock_frontendBridge_instr_uncache_out_a_valid
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_valid),
    .auto_memBlock_frontendBridge_instr_uncache_out_a_bits_param
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_param),
    .auto_memBlock_frontendBridge_instr_uncache_out_a_bits_address
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_address),
    .auto_memBlock_frontendBridge_instr_uncache_out_a_bits_corrupt
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_corrupt),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_ready
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_d_ready),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_valid
      (_l2top_auto_i_mmio_buffer_in_d_valid),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_opcode
      (_l2top_auto_i_mmio_buffer_in_d_bits_opcode),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_param
      (_l2top_auto_i_mmio_buffer_in_d_bits_param),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_size
      (_l2top_auto_i_mmio_buffer_in_d_bits_size),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_source
      (_l2top_auto_i_mmio_buffer_in_d_bits_source),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_sink
      (_l2top_auto_i_mmio_buffer_in_d_bits_sink),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_denied
      (_l2top_auto_i_mmio_buffer_in_d_bits_denied),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_data
      (_l2top_auto_i_mmio_buffer_in_d_bits_data),
    .auto_memBlock_frontendBridge_instr_uncache_out_d_bits_corrupt
      (_l2top_auto_i_mmio_buffer_in_d_bits_corrupt),
    .auto_memBlock_frontendBridge_icache_out_a_ready
      (_l2top_auto_xbar_in_1_a_ready),
    .auto_memBlock_frontendBridge_icache_out_a_valid
      (_core_auto_memBlock_frontendBridge_icache_out_a_valid),
    .auto_memBlock_frontendBridge_icache_out_a_bits_opcode
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_opcode),
    .auto_memBlock_frontendBridge_icache_out_a_bits_param
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_param),
    .auto_memBlock_frontendBridge_icache_out_a_bits_size
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_size),
    .auto_memBlock_frontendBridge_icache_out_a_bits_source
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_source),
    .auto_memBlock_frontendBridge_icache_out_a_bits_address
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_address),
    .auto_memBlock_frontendBridge_icache_out_a_bits_user_alias
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_user_alias),
    .auto_memBlock_frontendBridge_icache_out_a_bits_user_reqSource
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_user_reqSource),
    .auto_memBlock_frontendBridge_icache_out_a_bits_user_needHint
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_user_needHint),
    .auto_memBlock_frontendBridge_icache_out_a_bits_mask
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_mask),
    .auto_memBlock_frontendBridge_icache_out_a_bits_data
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_data),
    .auto_memBlock_frontendBridge_icache_out_a_bits_corrupt
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_corrupt),
    .auto_memBlock_frontendBridge_icache_out_d_ready
      (_core_auto_memBlock_frontendBridge_icache_out_d_ready),
    .auto_memBlock_frontendBridge_icache_out_d_valid
      (_l2top_auto_xbar_in_1_d_valid),
    .auto_memBlock_frontendBridge_icache_out_d_bits_opcode
      (_l2top_auto_xbar_in_1_d_bits_opcode),
    .auto_memBlock_frontendBridge_icache_out_d_bits_param
      (_l2top_auto_xbar_in_1_d_bits_param),
    .auto_memBlock_frontendBridge_icache_out_d_bits_size
      (_l2top_auto_xbar_in_1_d_bits_size),
    .auto_memBlock_frontendBridge_icache_out_d_bits_source
      (_l2top_auto_xbar_in_1_d_bits_source),
    .auto_memBlock_frontendBridge_icache_out_d_bits_sink
      (_l2top_auto_xbar_in_1_d_bits_sink),
    .auto_memBlock_frontendBridge_icache_out_d_bits_denied
      (_l2top_auto_xbar_in_1_d_bits_denied),
    .auto_memBlock_frontendBridge_icache_out_d_bits_data
      (_l2top_auto_xbar_in_1_d_bits_data),
    .auto_memBlock_frontendBridge_icache_out_d_bits_corrupt
      (_l2top_auto_xbar_in_1_d_bits_corrupt),
    .auto_memBlock_ptw_to_l2_buffer_out_a_ready
      (_l2top_auto_ptw_to_l2_buffer_in_a_ready),
    .auto_memBlock_ptw_to_l2_buffer_out_a_valid
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_valid),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_opcode
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_opcode),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_param
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_param),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_size
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_size),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_source
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_source),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_address
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_address),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_user_reqSource
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_user_reqSource),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_mask
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_mask),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_data
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_data),
    .auto_memBlock_ptw_to_l2_buffer_out_a_bits_corrupt
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_corrupt),
    .auto_memBlock_ptw_to_l2_buffer_out_d_ready
      (_core_auto_memBlock_ptw_to_l2_buffer_out_d_ready),
    .auto_memBlock_ptw_to_l2_buffer_out_d_valid
      (_l2top_auto_ptw_to_l2_buffer_in_d_valid),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_opcode
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_opcode),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_param
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_param),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_size
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_size),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_source
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_source),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_sink
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_sink),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_denied
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_denied),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_data
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_data),
    .auto_memBlock_ptw_to_l2_buffer_out_d_bits_corrupt
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_corrupt),
    .auto_memBlock_uncache_client_out_a_ready
      (_l2top_auto_buffers_in_a_ready),
    .auto_memBlock_uncache_client_out_a_valid
      (_core_auto_memBlock_uncache_client_out_a_valid),
    .auto_memBlock_uncache_client_out_a_bits_opcode
      (_core_auto_memBlock_uncache_client_out_a_bits_opcode),
    .auto_memBlock_uncache_client_out_a_bits_size
      (_core_auto_memBlock_uncache_client_out_a_bits_size),
    .auto_memBlock_uncache_client_out_a_bits_source
      (_core_auto_memBlock_uncache_client_out_a_bits_source),
    .auto_memBlock_uncache_client_out_a_bits_address
      (_core_auto_memBlock_uncache_client_out_a_bits_address),
    .auto_memBlock_uncache_client_out_a_bits_mask
      (_core_auto_memBlock_uncache_client_out_a_bits_mask),
    .auto_memBlock_uncache_client_out_a_bits_data
      (_core_auto_memBlock_uncache_client_out_a_bits_data),
    .auto_memBlock_uncache_client_out_d_ready
      (_core_auto_memBlock_uncache_client_out_d_ready),
    .auto_memBlock_uncache_client_out_d_valid
      (_l2top_auto_buffers_in_d_valid),
    .auto_memBlock_uncache_client_out_d_bits_opcode
      (_l2top_auto_buffers_in_d_bits_opcode),
    .auto_memBlock_uncache_client_out_d_bits_denied
      (_l2top_auto_buffers_in_d_bits_denied),
    .auto_memBlock_uncache_client_out_d_bits_data
      (_l2top_auto_buffers_in_d_bits_data),
    .auto_memBlock_plic_int_sink_in_1_0
      (_l2top_auto_plic_int_out_1_0),
    .auto_memBlock_plic_int_sink_in_0_0
      (_l2top_auto_plic_int_out_0_0),
    .auto_memBlock_debug_int_sink_in_0
      (_l2top_auto_debug_int_out_0),
    .auto_memBlock_clint_int_sink_in_0
      (_l2top_auto_clint_int_out_0),
    .auto_memBlock_clint_int_sink_in_1
      (_l2top_auto_clint_int_out_1),
    .auto_memBlock_l2_pf_sender_out_addr
      (_core_auto_memBlock_l2_pf_sender_out_addr),
    .auto_memBlock_l2_pf_sender_out_pf_source
      (_core_auto_memBlock_l2_pf_sender_out_pf_source),
    .auto_memBlock_l2_pf_sender_out_addr_valid
      (_core_auto_memBlock_l2_pf_sender_out_addr_valid),
    .auto_memBlock_l2_pf_sender_out_l2_pf_en
      (_core_auto_memBlock_l2_pf_sender_out_l2_pf_en),
    .auto_memBlock_dcache_client_out_a_ready
      (_l2top_auto_xbar_in_0_a_ready),
    .auto_memBlock_dcache_client_out_a_valid
      (_core_auto_memBlock_dcache_client_out_a_valid),
    .auto_memBlock_dcache_client_out_a_bits_opcode
      (_core_auto_memBlock_dcache_client_out_a_bits_opcode),
    .auto_memBlock_dcache_client_out_a_bits_param
      (_core_auto_memBlock_dcache_client_out_a_bits_param),
    .auto_memBlock_dcache_client_out_a_bits_size
      (_core_auto_memBlock_dcache_client_out_a_bits_size),
    .auto_memBlock_dcache_client_out_a_bits_source
      (_core_auto_memBlock_dcache_client_out_a_bits_source),
    .auto_memBlock_dcache_client_out_a_bits_address
      (_core_auto_memBlock_dcache_client_out_a_bits_address),
    .auto_memBlock_dcache_client_out_a_bits_user_alias
      (_core_auto_memBlock_dcache_client_out_a_bits_user_alias),
    .auto_memBlock_dcache_client_out_a_bits_user_vaddr
      (_core_auto_memBlock_dcache_client_out_a_bits_user_vaddr),
    .auto_memBlock_dcache_client_out_a_bits_user_reqSource
      (_core_auto_memBlock_dcache_client_out_a_bits_user_reqSource),
    .auto_memBlock_dcache_client_out_a_bits_user_needHint
      (_core_auto_memBlock_dcache_client_out_a_bits_user_needHint),
    .auto_memBlock_dcache_client_out_a_bits_echo_isKeyword
      (_core_auto_memBlock_dcache_client_out_a_bits_echo_isKeyword),
    .auto_memBlock_dcache_client_out_a_bits_mask
      (_core_auto_memBlock_dcache_client_out_a_bits_mask),
    .auto_memBlock_dcache_client_out_a_bits_data
      (_core_auto_memBlock_dcache_client_out_a_bits_data),
    .auto_memBlock_dcache_client_out_a_bits_corrupt
      (_core_auto_memBlock_dcache_client_out_a_bits_corrupt),
    .auto_memBlock_dcache_client_out_b_ready
      (_core_auto_memBlock_dcache_client_out_b_ready),
    .auto_memBlock_dcache_client_out_b_valid
      (_l2top_auto_xbar_in_0_b_valid),
    .auto_memBlock_dcache_client_out_b_bits_opcode
      (_l2top_auto_xbar_in_0_b_bits_opcode),
    .auto_memBlock_dcache_client_out_b_bits_param
      (_l2top_auto_xbar_in_0_b_bits_param),
    .auto_memBlock_dcache_client_out_b_bits_size
      (_l2top_auto_xbar_in_0_b_bits_size),
    .auto_memBlock_dcache_client_out_b_bits_source
      (_l2top_auto_xbar_in_0_b_bits_source),
    .auto_memBlock_dcache_client_out_b_bits_address
      (_l2top_auto_xbar_in_0_b_bits_address),
    .auto_memBlock_dcache_client_out_b_bits_mask
      (_l2top_auto_xbar_in_0_b_bits_mask),
    .auto_memBlock_dcache_client_out_b_bits_data
      (_l2top_auto_xbar_in_0_b_bits_data),
    .auto_memBlock_dcache_client_out_b_bits_corrupt
      (_l2top_auto_xbar_in_0_b_bits_corrupt),
    .auto_memBlock_dcache_client_out_c_ready
      (_l2top_auto_xbar_in_0_c_ready),
    .auto_memBlock_dcache_client_out_c_valid
      (_core_auto_memBlock_dcache_client_out_c_valid),
    .auto_memBlock_dcache_client_out_c_bits_opcode
      (_core_auto_memBlock_dcache_client_out_c_bits_opcode),
    .auto_memBlock_dcache_client_out_c_bits_param
      (_core_auto_memBlock_dcache_client_out_c_bits_param),
    .auto_memBlock_dcache_client_out_c_bits_size
      (_core_auto_memBlock_dcache_client_out_c_bits_size),
    .auto_memBlock_dcache_client_out_c_bits_source
      (_core_auto_memBlock_dcache_client_out_c_bits_source),
    .auto_memBlock_dcache_client_out_c_bits_address
      (_core_auto_memBlock_dcache_client_out_c_bits_address),
    .auto_memBlock_dcache_client_out_c_bits_user_alias
      (_core_auto_memBlock_dcache_client_out_c_bits_user_alias),
    .auto_memBlock_dcache_client_out_c_bits_user_vaddr
      (_core_auto_memBlock_dcache_client_out_c_bits_user_vaddr),
    .auto_memBlock_dcache_client_out_c_bits_user_reqSource
      (_core_auto_memBlock_dcache_client_out_c_bits_user_reqSource),
    .auto_memBlock_dcache_client_out_c_bits_user_needHint
      (_core_auto_memBlock_dcache_client_out_c_bits_user_needHint),
    .auto_memBlock_dcache_client_out_c_bits_echo_isKeyword
      (_core_auto_memBlock_dcache_client_out_c_bits_echo_isKeyword),
    .auto_memBlock_dcache_client_out_c_bits_data
      (_core_auto_memBlock_dcache_client_out_c_bits_data),
    .auto_memBlock_dcache_client_out_c_bits_corrupt
      (_core_auto_memBlock_dcache_client_out_c_bits_corrupt),
    .auto_memBlock_dcache_client_out_d_ready
      (_core_auto_memBlock_dcache_client_out_d_ready),
    .auto_memBlock_dcache_client_out_d_valid
      (_l2top_auto_xbar_in_0_d_valid),
    .auto_memBlock_dcache_client_out_d_bits_opcode
      (_l2top_auto_xbar_in_0_d_bits_opcode),
    .auto_memBlock_dcache_client_out_d_bits_param
      (_l2top_auto_xbar_in_0_d_bits_param),
    .auto_memBlock_dcache_client_out_d_bits_size
      (_l2top_auto_xbar_in_0_d_bits_size),
    .auto_memBlock_dcache_client_out_d_bits_source
      (_l2top_auto_xbar_in_0_d_bits_source),
    .auto_memBlock_dcache_client_out_d_bits_sink
      (_l2top_auto_xbar_in_0_d_bits_sink),
    .auto_memBlock_dcache_client_out_d_bits_denied
      (_l2top_auto_xbar_in_0_d_bits_denied),
    .auto_memBlock_dcache_client_out_d_bits_echo_isKeyword
      (_l2top_auto_xbar_in_0_d_bits_echo_isKeyword),
    .auto_memBlock_dcache_client_out_d_bits_data
      (_l2top_auto_xbar_in_0_d_bits_data),
    .auto_memBlock_dcache_client_out_d_bits_corrupt
      (_l2top_auto_xbar_in_0_d_bits_corrupt),
    .auto_memBlock_dcache_client_out_e_ready
      (_l2top_auto_xbar_in_0_e_ready),
    .auto_memBlock_dcache_client_out_e_valid
      (_core_auto_memBlock_dcache_client_out_e_valid),
    .auto_memBlock_dcache_client_out_e_bits_sink
      (_core_auto_memBlock_dcache_client_out_e_bits_sink),
    .io_hartId
      (_l2top_hartId_toCore[5:0]),
    .io_msiInfo_valid                                              (io_msiInfo_valid),
    .io_msiInfo_bits_info                                          (io_msiInfo_bits_info),
    .io_clintTime_valid                                            (io_clintTime_valid),
    .io_clintTime_bits                                             (io_clintTime_bits),
    .io_reset_vector
      (_l2top_reset_vector_toCore),
    .io_cpu_halt                                                   (_core_io_cpu_halt),
    .io_beu_errors_icache_ecc_error_valid
      (_core_io_beu_errors_icache_ecc_error_valid),
    .io_beu_errors_icache_ecc_error_bits
      (_core_io_beu_errors_icache_ecc_error_bits),
    .io_beu_errors_dcache_ecc_error_valid
      (_core_io_beu_errors_dcache_ecc_error_valid),
    .io_beu_errors_dcache_ecc_error_bits
      (_core_io_beu_errors_dcache_ecc_error_bits),
    .io_l2_hint_valid                                              (_l2top_l2_hint_valid),
    .io_l2_hint_bits_sourceId
      (_l2top_l2_hint_bits_sourceId),
    .io_l2_hint_bits_isKeyword
      (_l2top_l2_hint_bits_isKeyword),
    .io_l2_tlb_req_req_valid
      (_l2top_l2_tlb_req_req_valid),
    .io_l2_tlb_req_req_bits_vaddr
      (_l2top_l2_tlb_req_req_bits_vaddr),
    .io_l2_tlb_req_req_bits_cmd
      (_l2top_l2_tlb_req_req_bits_cmd),
    .io_l2_tlb_req_req_bits_kill
      (_l2top_l2_tlb_req_req_bits_kill),
    .io_l2_tlb_req_req_bits_no_translate
      (_l2top_l2_tlb_req_req_bits_no_translate),
    .io_l2_tlb_req_resp_valid
      (_core_io_l2_tlb_req_resp_valid),
    .io_l2_tlb_req_resp_bits_paddr_0
      (_core_io_l2_tlb_req_resp_bits_paddr_0),
    .io_l2_tlb_req_resp_bits_miss
      (_core_io_l2_tlb_req_resp_bits_miss),
    .io_l2_tlb_req_resp_bits_excp_0_pf_ld
      (_core_io_l2_tlb_req_resp_bits_excp_0_pf_ld),
    .io_l2_tlb_req_resp_bits_excp_0_pf_st
      (_core_io_l2_tlb_req_resp_bits_excp_0_pf_st),
    .io_l2_tlb_req_resp_bits_excp_0_af_ld
      (_core_io_l2_tlb_req_resp_bits_excp_0_af_ld),
    .io_l2_tlb_req_resp_bits_excp_0_af_st
      (_core_io_l2_tlb_req_resp_bits_excp_0_af_st),
    .io_l2_pmp_resp_mmio
      (_core_io_l2_pmp_resp_mmio)
  );
  L2Top l2top (
    .clock                                          (clock),
    .reset                                          (reset),
    .auto_buffers_in_a_ready                        (_l2top_auto_buffers_in_a_ready),
    .auto_buffers_in_a_valid
      (_core_auto_memBlock_uncache_client_out_a_valid),
    .auto_buffers_in_a_bits_opcode
      (_core_auto_memBlock_uncache_client_out_a_bits_opcode),
    .auto_buffers_in_a_bits_size
      (_core_auto_memBlock_uncache_client_out_a_bits_size),
    .auto_buffers_in_a_bits_source
      (_core_auto_memBlock_uncache_client_out_a_bits_source),
    .auto_buffers_in_a_bits_address
      (_core_auto_memBlock_uncache_client_out_a_bits_address),
    .auto_buffers_in_a_bits_mask
      (_core_auto_memBlock_uncache_client_out_a_bits_mask),
    .auto_buffers_in_a_bits_data
      (_core_auto_memBlock_uncache_client_out_a_bits_data),
    .auto_buffers_in_d_ready
      (_core_auto_memBlock_uncache_client_out_d_ready),
    .auto_buffers_in_d_valid                        (_l2top_auto_buffers_in_d_valid),
    .auto_buffers_in_d_bits_opcode
      (_l2top_auto_buffers_in_d_bits_opcode),
    .auto_buffers_in_d_bits_denied
      (_l2top_auto_buffers_in_d_bits_denied),
    .auto_buffers_in_d_bits_data                    (_l2top_auto_buffers_in_d_bits_data),
    .auto_l2cache_pf_recv_in_addr
      (_core_auto_memBlock_l2_pf_sender_out_addr),
    .auto_l2cache_pf_recv_in_pf_source
      (_core_auto_memBlock_l2_pf_sender_out_pf_source),
    .auto_l2cache_pf_recv_in_addr_valid
      (_core_auto_memBlock_l2_pf_sender_out_addr_valid),
    .auto_l2cache_pf_recv_in_l2_pf_en
      (_core_auto_memBlock_l2_pf_sender_out_l2_pf_en),
    .auto_i_mmio_buffer_in_a_ready
      (_l2top_auto_i_mmio_buffer_in_a_ready),
    .auto_i_mmio_buffer_in_a_valid
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_valid),
    .auto_i_mmio_buffer_in_a_bits_param
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_param),
    .auto_i_mmio_buffer_in_a_bits_address
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_address),
    .auto_i_mmio_buffer_in_a_bits_corrupt
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_a_bits_corrupt),
    .auto_i_mmio_buffer_in_d_ready
      (_core_auto_memBlock_frontendBridge_instr_uncache_out_d_ready),
    .auto_i_mmio_buffer_in_d_valid
      (_l2top_auto_i_mmio_buffer_in_d_valid),
    .auto_i_mmio_buffer_in_d_bits_opcode
      (_l2top_auto_i_mmio_buffer_in_d_bits_opcode),
    .auto_i_mmio_buffer_in_d_bits_param
      (_l2top_auto_i_mmio_buffer_in_d_bits_param),
    .auto_i_mmio_buffer_in_d_bits_size
      (_l2top_auto_i_mmio_buffer_in_d_bits_size),
    .auto_i_mmio_buffer_in_d_bits_source
      (_l2top_auto_i_mmio_buffer_in_d_bits_source),
    .auto_i_mmio_buffer_in_d_bits_sink
      (_l2top_auto_i_mmio_buffer_in_d_bits_sink),
    .auto_i_mmio_buffer_in_d_bits_denied
      (_l2top_auto_i_mmio_buffer_in_d_bits_denied),
    .auto_i_mmio_buffer_in_d_bits_data
      (_l2top_auto_i_mmio_buffer_in_d_bits_data),
    .auto_i_mmio_buffer_in_d_bits_corrupt
      (_l2top_auto_i_mmio_buffer_in_d_bits_corrupt),
    .auto_ptw_to_l2_buffer_in_a_ready
      (_l2top_auto_ptw_to_l2_buffer_in_a_ready),
    .auto_ptw_to_l2_buffer_in_a_valid
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_valid),
    .auto_ptw_to_l2_buffer_in_a_bits_opcode
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_opcode),
    .auto_ptw_to_l2_buffer_in_a_bits_param
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_param),
    .auto_ptw_to_l2_buffer_in_a_bits_size
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_size),
    .auto_ptw_to_l2_buffer_in_a_bits_source
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_source),
    .auto_ptw_to_l2_buffer_in_a_bits_address
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_address),
    .auto_ptw_to_l2_buffer_in_a_bits_user_reqSource
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_user_reqSource),
    .auto_ptw_to_l2_buffer_in_a_bits_mask
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_mask),
    .auto_ptw_to_l2_buffer_in_a_bits_data
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_data),
    .auto_ptw_to_l2_buffer_in_a_bits_corrupt
      (_core_auto_memBlock_ptw_to_l2_buffer_out_a_bits_corrupt),
    .auto_ptw_to_l2_buffer_in_d_ready
      (_core_auto_memBlock_ptw_to_l2_buffer_out_d_ready),
    .auto_ptw_to_l2_buffer_in_d_valid
      (_l2top_auto_ptw_to_l2_buffer_in_d_valid),
    .auto_ptw_to_l2_buffer_in_d_bits_opcode
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_opcode),
    .auto_ptw_to_l2_buffer_in_d_bits_param
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_param),
    .auto_ptw_to_l2_buffer_in_d_bits_size
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_size),
    .auto_ptw_to_l2_buffer_in_d_bits_source
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_source),
    .auto_ptw_to_l2_buffer_in_d_bits_sink
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_sink),
    .auto_ptw_to_l2_buffer_in_d_bits_denied
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_denied),
    .auto_ptw_to_l2_buffer_in_d_bits_data
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_data),
    .auto_ptw_to_l2_buffer_in_d_bits_corrupt
      (_l2top_auto_ptw_to_l2_buffer_in_d_bits_corrupt),
    .auto_beu_int_out_0                             (auto_l2top_beu_int_out_0),
    .auto_xbar_in_1_a_ready                         (_l2top_auto_xbar_in_1_a_ready),
    .auto_xbar_in_1_a_valid
      (_core_auto_memBlock_frontendBridge_icache_out_a_valid),
    .auto_xbar_in_1_a_bits_opcode
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_opcode),
    .auto_xbar_in_1_a_bits_param
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_param),
    .auto_xbar_in_1_a_bits_size
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_size),
    .auto_xbar_in_1_a_bits_source
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_source),
    .auto_xbar_in_1_a_bits_address
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_address),
    .auto_xbar_in_1_a_bits_user_alias
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_user_alias),
    .auto_xbar_in_1_a_bits_user_reqSource
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_user_reqSource),
    .auto_xbar_in_1_a_bits_user_needHint
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_user_needHint),
    .auto_xbar_in_1_a_bits_mask
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_mask),
    .auto_xbar_in_1_a_bits_data
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_data),
    .auto_xbar_in_1_a_bits_corrupt
      (_core_auto_memBlock_frontendBridge_icache_out_a_bits_corrupt),
    .auto_xbar_in_1_d_ready
      (_core_auto_memBlock_frontendBridge_icache_out_d_ready),
    .auto_xbar_in_1_d_valid                         (_l2top_auto_xbar_in_1_d_valid),
    .auto_xbar_in_1_d_bits_opcode                   (_l2top_auto_xbar_in_1_d_bits_opcode),
    .auto_xbar_in_1_d_bits_param                    (_l2top_auto_xbar_in_1_d_bits_param),
    .auto_xbar_in_1_d_bits_size                     (_l2top_auto_xbar_in_1_d_bits_size),
    .auto_xbar_in_1_d_bits_source                   (_l2top_auto_xbar_in_1_d_bits_source),
    .auto_xbar_in_1_d_bits_sink                     (_l2top_auto_xbar_in_1_d_bits_sink),
    .auto_xbar_in_1_d_bits_denied                   (_l2top_auto_xbar_in_1_d_bits_denied),
    .auto_xbar_in_1_d_bits_data                     (_l2top_auto_xbar_in_1_d_bits_data),
    .auto_xbar_in_1_d_bits_corrupt
      (_l2top_auto_xbar_in_1_d_bits_corrupt),
    .auto_xbar_in_0_a_ready                         (_l2top_auto_xbar_in_0_a_ready),
    .auto_xbar_in_0_a_valid
      (_core_auto_memBlock_dcache_client_out_a_valid),
    .auto_xbar_in_0_a_bits_opcode
      (_core_auto_memBlock_dcache_client_out_a_bits_opcode),
    .auto_xbar_in_0_a_bits_param
      (_core_auto_memBlock_dcache_client_out_a_bits_param),
    .auto_xbar_in_0_a_bits_size
      (_core_auto_memBlock_dcache_client_out_a_bits_size),
    .auto_xbar_in_0_a_bits_source
      (_core_auto_memBlock_dcache_client_out_a_bits_source),
    .auto_xbar_in_0_a_bits_address
      (_core_auto_memBlock_dcache_client_out_a_bits_address),
    .auto_xbar_in_0_a_bits_user_alias
      (_core_auto_memBlock_dcache_client_out_a_bits_user_alias),
    .auto_xbar_in_0_a_bits_user_vaddr
      (_core_auto_memBlock_dcache_client_out_a_bits_user_vaddr),
    .auto_xbar_in_0_a_bits_user_reqSource
      (_core_auto_memBlock_dcache_client_out_a_bits_user_reqSource),
    .auto_xbar_in_0_a_bits_user_needHint
      (_core_auto_memBlock_dcache_client_out_a_bits_user_needHint),
    .auto_xbar_in_0_a_bits_echo_isKeyword
      (_core_auto_memBlock_dcache_client_out_a_bits_echo_isKeyword),
    .auto_xbar_in_0_a_bits_mask
      (_core_auto_memBlock_dcache_client_out_a_bits_mask),
    .auto_xbar_in_0_a_bits_data
      (_core_auto_memBlock_dcache_client_out_a_bits_data),
    .auto_xbar_in_0_a_bits_corrupt
      (_core_auto_memBlock_dcache_client_out_a_bits_corrupt),
    .auto_xbar_in_0_b_ready
      (_core_auto_memBlock_dcache_client_out_b_ready),
    .auto_xbar_in_0_b_valid                         (_l2top_auto_xbar_in_0_b_valid),
    .auto_xbar_in_0_b_bits_opcode                   (_l2top_auto_xbar_in_0_b_bits_opcode),
    .auto_xbar_in_0_b_bits_param                    (_l2top_auto_xbar_in_0_b_bits_param),
    .auto_xbar_in_0_b_bits_size                     (_l2top_auto_xbar_in_0_b_bits_size),
    .auto_xbar_in_0_b_bits_source                   (_l2top_auto_xbar_in_0_b_bits_source),
    .auto_xbar_in_0_b_bits_address
      (_l2top_auto_xbar_in_0_b_bits_address),
    .auto_xbar_in_0_b_bits_mask                     (_l2top_auto_xbar_in_0_b_bits_mask),
    .auto_xbar_in_0_b_bits_data                     (_l2top_auto_xbar_in_0_b_bits_data),
    .auto_xbar_in_0_b_bits_corrupt
      (_l2top_auto_xbar_in_0_b_bits_corrupt),
    .auto_xbar_in_0_c_ready                         (_l2top_auto_xbar_in_0_c_ready),
    .auto_xbar_in_0_c_valid
      (_core_auto_memBlock_dcache_client_out_c_valid),
    .auto_xbar_in_0_c_bits_opcode
      (_core_auto_memBlock_dcache_client_out_c_bits_opcode),
    .auto_xbar_in_0_c_bits_param
      (_core_auto_memBlock_dcache_client_out_c_bits_param),
    .auto_xbar_in_0_c_bits_size
      (_core_auto_memBlock_dcache_client_out_c_bits_size),
    .auto_xbar_in_0_c_bits_source
      (_core_auto_memBlock_dcache_client_out_c_bits_source),
    .auto_xbar_in_0_c_bits_address
      (_core_auto_memBlock_dcache_client_out_c_bits_address),
    .auto_xbar_in_0_c_bits_user_alias
      (_core_auto_memBlock_dcache_client_out_c_bits_user_alias),
    .auto_xbar_in_0_c_bits_user_vaddr
      (_core_auto_memBlock_dcache_client_out_c_bits_user_vaddr),
    .auto_xbar_in_0_c_bits_user_reqSource
      (_core_auto_memBlock_dcache_client_out_c_bits_user_reqSource),
    .auto_xbar_in_0_c_bits_user_needHint
      (_core_auto_memBlock_dcache_client_out_c_bits_user_needHint),
    .auto_xbar_in_0_c_bits_echo_isKeyword
      (_core_auto_memBlock_dcache_client_out_c_bits_echo_isKeyword),
    .auto_xbar_in_0_c_bits_data
      (_core_auto_memBlock_dcache_client_out_c_bits_data),
    .auto_xbar_in_0_c_bits_corrupt
      (_core_auto_memBlock_dcache_client_out_c_bits_corrupt),
    .auto_xbar_in_0_d_ready
      (_core_auto_memBlock_dcache_client_out_d_ready),
    .auto_xbar_in_0_d_valid                         (_l2top_auto_xbar_in_0_d_valid),
    .auto_xbar_in_0_d_bits_opcode                   (_l2top_auto_xbar_in_0_d_bits_opcode),
    .auto_xbar_in_0_d_bits_param                    (_l2top_auto_xbar_in_0_d_bits_param),
    .auto_xbar_in_0_d_bits_size                     (_l2top_auto_xbar_in_0_d_bits_size),
    .auto_xbar_in_0_d_bits_source                   (_l2top_auto_xbar_in_0_d_bits_source),
    .auto_xbar_in_0_d_bits_sink                     (_l2top_auto_xbar_in_0_d_bits_sink),
    .auto_xbar_in_0_d_bits_denied                   (_l2top_auto_xbar_in_0_d_bits_denied),
    .auto_xbar_in_0_d_bits_echo_isKeyword
      (_l2top_auto_xbar_in_0_d_bits_echo_isKeyword),
    .auto_xbar_in_0_d_bits_data                     (_l2top_auto_xbar_in_0_d_bits_data),
    .auto_xbar_in_0_d_bits_corrupt
      (_l2top_auto_xbar_in_0_d_bits_corrupt),
    .auto_xbar_in_0_e_ready                         (_l2top_auto_xbar_in_0_e_ready),
    .auto_xbar_in_0_e_valid
      (_core_auto_memBlock_dcache_client_out_e_valid),
    .auto_xbar_in_0_e_bits_sink
      (_core_auto_memBlock_dcache_client_out_e_bits_sink),
    .auto_plic_int_in_1_0                           (auto_l2top_plic_int_in_1_0),
    .auto_plic_int_in_0_0                           (auto_l2top_plic_int_in_0_0),
    .auto_plic_int_out_1_0                          (_l2top_auto_plic_int_out_1_0),
    .auto_plic_int_out_0_0                          (_l2top_auto_plic_int_out_0_0),
    .auto_debug_int_in_0                            (auto_l2top_debug_int_in_0),
    .auto_debug_int_out_0                           (_l2top_auto_debug_int_out_0),
    .auto_clint_int_in_0                            (auto_l2top_clint_int_in_0),
    .auto_clint_int_in_1                            (auto_l2top_clint_int_in_1),
    .auto_clint_int_out_0                           (_l2top_auto_clint_int_out_0),
    .auto_clint_int_out_1                           (_l2top_auto_clint_int_out_1),
    .beu_errors_icache_ecc_error_valid
      (_core_io_beu_errors_icache_ecc_error_valid),
    .beu_errors_icache_ecc_error_bits
      (_core_io_beu_errors_icache_ecc_error_bits),
    .beu_errors_dcache_ecc_error_valid
      (_core_io_beu_errors_dcache_ecc_error_valid),
    .beu_errors_dcache_ecc_error_bits
      (_core_io_beu_errors_dcache_ecc_error_bits),
    .reset_vector_fromTile                          (io_reset_vector),
    .reset_vector_toCore                            (_l2top_reset_vector_toCore),
    .hartId_fromTile                                ({58'h0, io_hartId}),
    .hartId_toCore                                  (_l2top_hartId_toCore),
    .cpu_halt_fromCore                              (_core_io_cpu_halt),
    .cpu_halt_toTile                                (io_cpu_halt),
    .chi_txsactive                                  (io_chi_txsactive),
    .chi_rxsactive                                  (io_chi_rxsactive),
    .chi_tx_linkactivereq                           (io_chi_tx_linkactivereq),
    .chi_tx_linkactiveack                           (io_chi_tx_linkactiveack),
    .chi_tx_req_flitpend                            (io_chi_tx_req_flitpend),
    .chi_tx_req_flitv                               (io_chi_tx_req_flitv),
    .chi_tx_req_flit                                (io_chi_tx_req_flit),
    .chi_tx_req_lcrdv                               (io_chi_tx_req_lcrdv),
    .chi_tx_rsp_flitpend                            (io_chi_tx_rsp_flitpend),
    .chi_tx_rsp_flitv                               (io_chi_tx_rsp_flitv),
    .chi_tx_rsp_flit                                (io_chi_tx_rsp_flit),
    .chi_tx_rsp_lcrdv                               (io_chi_tx_rsp_lcrdv),
    .chi_tx_dat_flitpend                            (io_chi_tx_dat_flitpend),
    .chi_tx_dat_flitv                               (io_chi_tx_dat_flitv),
    .chi_tx_dat_flit                                (io_chi_tx_dat_flit),
    .chi_tx_dat_lcrdv                               (io_chi_tx_dat_lcrdv),
    .chi_rx_linkactivereq                           (io_chi_rx_linkactivereq),
    .chi_rx_linkactiveack                           (io_chi_rx_linkactiveack),
    .chi_rx_rsp_flitpend                            (io_chi_rx_rsp_flitpend),
    .chi_rx_rsp_flitv                               (io_chi_rx_rsp_flitv),
    .chi_rx_rsp_flit                                (io_chi_rx_rsp_flit),
    .chi_rx_rsp_lcrdv                               (io_chi_rx_rsp_lcrdv),
    .chi_rx_dat_flitpend                            (io_chi_rx_dat_flitpend),
    .chi_rx_dat_flitv                               (io_chi_rx_dat_flitv),
    .chi_rx_dat_flit                                (io_chi_rx_dat_flit),
    .chi_rx_dat_lcrdv                               (io_chi_rx_dat_lcrdv),
    .chi_rx_snp_flitpend                            (io_chi_rx_snp_flitpend),
    .chi_rx_snp_flitv                               (io_chi_rx_snp_flitv),
    .chi_rx_snp_flit                                (io_chi_rx_snp_flit),
    .chi_rx_snp_lcrdv                               (io_chi_rx_snp_lcrdv),
    .nodeID                                         (io_nodeID),
    .l2_tlb_req_req_valid                           (_l2top_l2_tlb_req_req_valid),
    .l2_tlb_req_req_bits_vaddr                      (_l2top_l2_tlb_req_req_bits_vaddr),
    .l2_tlb_req_req_bits_cmd                        (_l2top_l2_tlb_req_req_bits_cmd),
    .l2_tlb_req_req_bits_kill                       (_l2top_l2_tlb_req_req_bits_kill),
    .l2_tlb_req_req_bits_no_translate
      (_l2top_l2_tlb_req_req_bits_no_translate),
    .l2_tlb_req_resp_valid                          (_core_io_l2_tlb_req_resp_valid),
    .l2_tlb_req_resp_bits_paddr_0
      (_core_io_l2_tlb_req_resp_bits_paddr_0),
    .l2_tlb_req_resp_bits_miss                      (_core_io_l2_tlb_req_resp_bits_miss),
    .l2_tlb_req_resp_bits_excp_0_pf_ld
      (_core_io_l2_tlb_req_resp_bits_excp_0_pf_ld),
    .l2_tlb_req_resp_bits_excp_0_pf_st
      (_core_io_l2_tlb_req_resp_bits_excp_0_pf_st),
    .l2_tlb_req_resp_bits_excp_0_af_ld
      (_core_io_l2_tlb_req_resp_bits_excp_0_af_ld),
    .l2_tlb_req_resp_bits_excp_0_af_st
      (_core_io_l2_tlb_req_resp_bits_excp_0_af_st),
    .l2_pmp_resp_mmio                               (_core_io_l2_pmp_resp_mmio),
    .l2_hint_valid                                  (_l2top_l2_hint_valid),
    .l2_hint_bits_sourceId                          (_l2top_l2_hint_bits_sourceId),
    .l2_hint_bits_isKeyword                         (_l2top_l2_hint_bits_isKeyword)
  );
endmodule

